$axure.loadCurrentPage({
  "url":"奖品领取详情.html",
  "generationDate":new Date(1425625656903.32),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c885b41402c840d6b57a32010a7d0032",
    "type":"Axure:Page",
    "name":"奖品领取详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFF666666},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"263dc613810b4632a4dca1efaece2921",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":10},
            "size":{
              "width":976,
              "height":753}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6b8d1e52f2f474e967a8fe4480f788c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":10},
                "size":{
                  "width":976,
                  "height":753}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/奖品领取详情/u0.png"}},
{
          "id":"ff02e207ceb64c3c94cefd9f5ff3bd75",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":186,
              "y":180},
            "size":{
              "width":694,
              "height":521}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b76e2fe1bee40b8be971dcd0a4678ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":186,
                  "y":180},
                "size":{
                  "width":694,
                  "height":521}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/奖品领取详情/u2.png"}},
{
          "id":"8fcb78026168430e96351de001d48636",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":280,
              "y":210},
            "size":{
              "width":378,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69c0d0acfdae4fdda775da18ff3df681",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":210,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"117af59e385f4eb7a00406d94a4d2a52",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":210,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/奖品领取详情/u5.png"}},
{
              "id":"120abae5360f452aa2105e8087e7574d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":210,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"21b3efc847d9460a8e561d4504645972",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":210,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/奖品领取详情/u5.png"}},
{
              "id":"4e5d4a83181c44119a09c2f9f2727ae1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":72},
                "size":{
                  "width":210,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0add913b66be46a1b98aef84392c174b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":72},
                    "size":{
                      "width":210,
                      "height":34},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/奖品领取详情/u13.png"}},
{
              "id":"584ee740ae424ede924070d99df98267",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":210,
                  "y":0},
                "size":{
                  "width":168,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9638b8dd443144028c57a5f8f970c5f8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":210,
                      "y":0},
                    "size":{
                      "width":168,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/奖品领取详情/u7.png"}},
{
              "id":"ea8f315c6f6045a280d10145ba500439",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":210,
                  "y":36},
                "size":{
                  "width":168,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fea16cd807264f2c87fcffe30afa8991",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":210,
                      "y":36},
                    "size":{
                      "width":168,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/奖品领取详情/u7.png"}},
{
              "id":"43c225f726b745899c1eb7cd11c31f6b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":210,
                  "y":72},
                "size":{
                  "width":168,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"61a0621429624db3b5de572546b0402b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":210,
                      "y":72},
                    "size":{
                      "width":168,
                      "height":34},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/奖品领取详情/u15.png"}}]},
{
          "id":"0bdeaf2d52c94761b44d35dda1c0fdfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":607,
              "y":218},
            "size":{
              "width":10,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1117434dbddd4e2796dd96270158ca12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":607,
                  "y":218},
                "size":{
                  "width":10,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/奖品领取详情/u17.png"}},
{
          "id":"e18db114921f487abfe362ce46a003f9",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":90},
            "size":{
              "width":600,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a15fa1e953884460a30a806772be92b3",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":600,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"feef0a2aebd4470bbb09a2e7b2f6ec16",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cf1268e4a4864cfdac842dd352162ae4",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 工单管理",
                              "target":{
                                "targetType":"page",
                                "url":"工单管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u43.png"}},
{
                  "id":"88361b2e59b74119bdaa02574bff41c0",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ad9b8efe7e9442fdab19e94e93823178",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 账号管理",
                              "target":{
                                "targetType":"page",
                                "url":"账号管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u43.png"}},
{
                  "id":"3975fb7d0e2a4e67abb443c08f1e7cef",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1573009bbb644f1aab70b4bd7c9627e6",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 奖品管理",
                              "target":{
                                "targetType":"page",
                                "url":"奖品管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u43.png"}},
{
                  "id":"e60b910d4d9f4c558e893effe9348850",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2d9cfcb9e2b7497e918a151757bae2b3",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 积分中心",
                              "target":{
                                "targetType":"page",
                                "url":"积分中心.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u43.png"}},
{
                  "id":"f4c3aef913e9453fbae49d39cf2c19f4",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"300ea0a1ba834433b93896ab036a8ac9",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 系统设置",
                              "target":{
                                "targetType":"page",
                                "url":"系统设置.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u43.png"}},
{
                  "id":"b8bd83a6173e4107ae966f08044aaf6a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"14b6f85c2b2e4301a45a7b0cd62f5503",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":500,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 版本管理",
                              "target":{
                                "targetType":"page",
                                "url":"版本管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u53.png"}}]}]},
{
          "id":"6efb57bbf5c84635a8a2ccc9459c8cfb",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":261.5,
              "y":30},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录界面",
                      "target":{
                        "targetType":"page",
                        "url":"登录界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8a5e841cd1c74ce2b71c216158466209",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":140,
              "y":36},
            "size":{
              "width":104,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c0e57c32b134f2ea62189a8b330f734",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":140,
                  "y":36},
                "size":{
                  "width":104,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72df0f36952e444386dc005b7cc5db56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":186,
              "y":152},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2288f3be60674086a4aae976c3284d6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":186,
                  "y":152},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc6276af7f444554b51ce55316e6ceb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":252,
              "y":152},
            "size":{
              "width":11,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"073e157af4be43ff846ffc03c0fc525a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":252,
                  "y":152},
                "size":{
                  "width":11,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b291ca99a05847e692c480f20b5142b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":268,
              "y":151},
            "size":{
              "width":69,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0888a996e25c4ee3afd9b0f69e80702a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":268,
                  "y":151},
                "size":{
                  "width":69,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"984d7f39c05d423a917594416c7496ab",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":800,
              "y":146},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 奖品管理",
                      "target":{
                        "targetType":"page",
                        "url":"奖品管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "263dc613810b4632a4dca1efaece2921":{
      "scriptId":"u0"},
    "c6b8d1e52f2f474e967a8fe4480f788c":{
      "scriptId":"u1"},
    "ff02e207ceb64c3c94cefd9f5ff3bd75":{
      "scriptId":"u2"},
    "8b76e2fe1bee40b8be971dcd0a4678ef":{
      "scriptId":"u3"},
    "8fcb78026168430e96351de001d48636":{
      "scriptId":"u4"},
    "69c0d0acfdae4fdda775da18ff3df681":{
      "scriptId":"u5"},
    "117af59e385f4eb7a00406d94a4d2a52":{
      "scriptId":"u6"},
    "584ee740ae424ede924070d99df98267":{
      "scriptId":"u7"},
    "9638b8dd443144028c57a5f8f970c5f8":{
      "scriptId":"u8"},
    "120abae5360f452aa2105e8087e7574d":{
      "scriptId":"u9"},
    "21b3efc847d9460a8e561d4504645972":{
      "scriptId":"u10"},
    "ea8f315c6f6045a280d10145ba500439":{
      "scriptId":"u11"},
    "fea16cd807264f2c87fcffe30afa8991":{
      "scriptId":"u12"},
    "4e5d4a83181c44119a09c2f9f2727ae1":{
      "scriptId":"u13"},
    "0add913b66be46a1b98aef84392c174b":{
      "scriptId":"u14"},
    "43c225f726b745899c1eb7cd11c31f6b":{
      "scriptId":"u15"},
    "61a0621429624db3b5de572546b0402b":{
      "scriptId":"u16"},
    "0bdeaf2d52c94761b44d35dda1c0fdfb":{
      "scriptId":"u17"},
    "1117434dbddd4e2796dd96270158ca12":{
      "scriptId":"u18"},
    "e18db114921f487abfe362ce46a003f9":{
      "scriptId":"u19"},
    "a15fa1e953884460a30a806772be92b3":{
      "scriptId":"u20"},
    "feef0a2aebd4470bbb09a2e7b2f6ec16":{
      "scriptId":"u21"},
    "cf1268e4a4864cfdac842dd352162ae4":{
      "scriptId":"u22"},
    "88361b2e59b74119bdaa02574bff41c0":{
      "scriptId":"u23"},
    "ad9b8efe7e9442fdab19e94e93823178":{
      "scriptId":"u24"},
    "3975fb7d0e2a4e67abb443c08f1e7cef":{
      "scriptId":"u25"},
    "1573009bbb644f1aab70b4bd7c9627e6":{
      "scriptId":"u26"},
    "e60b910d4d9f4c558e893effe9348850":{
      "scriptId":"u27"},
    "2d9cfcb9e2b7497e918a151757bae2b3":{
      "scriptId":"u28"},
    "f4c3aef913e9453fbae49d39cf2c19f4":{
      "scriptId":"u29"},
    "300ea0a1ba834433b93896ab036a8ac9":{
      "scriptId":"u30"},
    "b8bd83a6173e4107ae966f08044aaf6a":{
      "scriptId":"u31"},
    "14b6f85c2b2e4301a45a7b0cd62f5503":{
      "scriptId":"u32"},
    "6efb57bbf5c84635a8a2ccc9459c8cfb":{
      "scriptId":"u33"},
    "8a5e841cd1c74ce2b71c216158466209":{
      "scriptId":"u34"},
    "5c0e57c32b134f2ea62189a8b330f734":{
      "scriptId":"u35"},
    "72df0f36952e444386dc005b7cc5db56":{
      "scriptId":"u36"},
    "2288f3be60674086a4aae976c3284d6b":{
      "scriptId":"u37"},
    "dc6276af7f444554b51ce55316e6ceb0":{
      "scriptId":"u38"},
    "073e157af4be43ff846ffc03c0fc525a":{
      "scriptId":"u39"},
    "b291ca99a05847e692c480f20b5142b3":{
      "scriptId":"u40"},
    "0888a996e25c4ee3afd9b0f69e80702a":{
      "scriptId":"u41"},
    "984d7f39c05d423a917594416c7496ab":{
      "scriptId":"u42"}}});