$axure.loadCurrentPage({
  "url":"about.html",
  "generationDate":new Date(1425627275247.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cb3f40b96165419e935cc88df05baf14",
    "type":"Axure:Page",
    "name":"about",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6abdd1f1ccdd4f3582340d112d86ec94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b1c2bf2df4c4e93ae10be6e1c09b87b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/slide/u0.png"}},
{
          "id":"8c23f4458f6a4fa7943948832b08d9c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"400f010b3e404f36862ebf92c1f9bbe7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/signup/u2.png"}},
{
          "id":"96e5f6e14db14b60aaffc04b3a0f15f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":15,
              "y":15},
            "size":{
              "width":30,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7a083a9f03e494891711dceb22ee43d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":15,
                  "y":15},
                "size":{
                  "width":30,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/signup/u4.png"}},
{
          "id":"111984414c914a9881131d815c7ed7ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "lineSpacing":"20px",
            "location":{
              "x":30,
              "y":80},
            "size":{
              "width":280,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36cd52e911b94be9ab17b42c71d2e000",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "lineSpacing":"20px",
                "location":{
                  "x":30,
                  "y":80},
                "size":{
                  "width":280,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6abdd1f1ccdd4f3582340d112d86ec94":{
      "scriptId":"u0"},
    "7b1c2bf2df4c4e93ae10be6e1c09b87b":{
      "scriptId":"u1"},
    "8c23f4458f6a4fa7943948832b08d9c0":{
      "scriptId":"u2"},
    "400f010b3e404f36862ebf92c1f9bbe7":{
      "scriptId":"u3"},
    "96e5f6e14db14b60aaffc04b3a0f15f4":{
      "scriptId":"u4"},
    "e7a083a9f03e494891711dceb22ee43d":{
      "scriptId":"u5"},
    "111984414c914a9881131d815c7ed7ae":{
      "scriptId":"u6"},
    "36cd52e911b94be9ab17b42c71d2e000":{
      "scriptId":"u7"}}});