$axure.loadCurrentPage({
  "url":"编辑关于.html",
  "generationDate":new Date(1425625658187.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0757488630864c488841407254808656",
    "type":"Axure:Page",
    "name":"编辑关于",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFF666666},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"289b090006064e5cb6947eb871f6c24e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":1010,
              "height":750}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"932b83e602964bbaa2af22e3153e224d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":1010,
                  "height":750}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑关于/u0.png"}},
{
          "id":"179b155c8e1e45f9804ba4576128845c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":190,
              "y":169},
            "size":{
              "width":670,
              "height":521}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d62c5747120c460eaf288041cf355983",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":190,
                  "y":169},
                "size":{
                  "width":670,
                  "height":521}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑关于/u2.png"}},
{
          "id":"5e8172fa91c44e30a07d351f42378223",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":255,
              "y":198},
            "size":{
              "width":500,
              "height":380}},
          "adaptiveStyles":{
}},
{
          "id":"53616cbfcf3a436a9681c0c772b0559d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":545,
              "y":603},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 关于",
                      "target":{
                        "targetType":"page",
                        "url":"关于.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6994fc3db9fa4dfd94cd9a1454b5080c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":645,
              "y":603},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 关于",
                      "target":{
                        "targetType":"page",
                        "url":"关于.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"5659051362384a1ba2acaaf4a32ffe72",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":183,
              "y":82},
            "size":{
              "width":600,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56a4f7191487472799b5416242aa392e",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":600,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9ace53e6e3434bc1ac8407553e69a1cc",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"422659f4d31c47349ec4736bfb53f5bf",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 工单管理",
                              "target":{
                                "targetType":"page",
                                "url":"工单管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u43.png"}},
{
                  "id":"3640b7182860495786c0a4f071a3567b",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c845b9ef90c6460db1962191e9ca11b4",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 账号管理",
                              "target":{
                                "targetType":"page",
                                "url":"账号管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u43.png"}},
{
                  "id":"0cde32b6d4fe4fafaad006e742e77232",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"86e1d5f13b4646f99c2078ae24818fc6",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 奖品管理",
                              "target":{
                                "targetType":"page",
                                "url":"奖品管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u43.png"}},
{
                  "id":"fb2cf3b747d24b868d45e5c9d91b4ee1",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ec9165718af346868f6628f064f90a9a",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 积分中心",
                              "target":{
                                "targetType":"page",
                                "url":"积分中心.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u43.png"}},
{
                  "id":"ca35eca00e7841ad95b99befe1c83668",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a0ce6e96446e47e3b32eae9e14bb9143",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 系统设置",
                              "target":{
                                "targetType":"page",
                                "url":"系统设置.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u43.png"}},
{
                  "id":"c26fe067bae048b49e3dc1ad0430ff9e",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1f8109a921f2412db2af064ceef41d4d",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":500,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 版本管理",
                              "target":{
                                "targetType":"page",
                                "url":"版本管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u53.png"}}]}]},
{
          "id":"2ca88ab9787442ec875184fd016d86f9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":214,
              "y":25},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录界面",
                      "target":{
                        "targetType":"page",
                        "url":"登录界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"62f916afe5a14981aa4622682f3fcc58",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":92,
              "y":31},
            "size":{
              "width":104,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09919cb0bcc34580a1ec4e1c2f161ecb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":92,
                  "y":31},
                "size":{
                  "width":104,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f3e3c6f0239484391d3379002c4c66b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":183,
              "y":140},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ed9b33ac6cb4109ba57e96f092a13c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":183,
                  "y":140},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fe47356d93f49ac92113ac281d5d338",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":250,
              "y":142},
            "size":{
              "width":11,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"228408854804433ca23551b5789b4616",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":250,
                  "y":142},
                "size":{
                  "width":11,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7f87a56ad254344937ec4643ebcaef7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":266,
              "y":140},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42a587e445f14db298b004aa8fc4d004",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":266,
                  "y":140},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8c9eceb6be847af882b48344f9f3073",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":790,
              "y":131},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 关于",
                      "target":{
                        "targetType":"page",
                        "url":"关于.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"5b26e9d56d424390ac53fb85ce42e3b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":303,
              "y":141},
            "size":{
              "width":11,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2259872064ad4913b306a797c7585646",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":303,
                  "y":141},
                "size":{
                  "width":11,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a130c0507ecb4cf0b81debf87b48a17b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":319,
              "y":139},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cb11408a24f46968d0fac9553b56cf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":319,
                  "y":139},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5711d25a531f481cba5b0fa62848107b",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":587,
              "y":112},
            "size":{
              "width":100,
              "height":183}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acad0bcf8850470b90c4f5e372560487",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":100,
                  "height":183}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4f29786e902d4360b9799952048a1433",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f74f9ddc432f4308b1629ec374423530",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 系统设置",
                              "target":{
                                "targetType":"page",
                                "url":"系统设置.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/关于/u36.png"}},
{
                  "id":"f1c48339bf644c74abef68eb582e599b",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":93},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fea88d8ca8064501bdebce9136e697c9",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":93},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 意见反馈",
                              "target":{
                                "targetType":"page",
                                "url":"意见反馈.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/关于/u42.png"}},
{
                  "id":"9c3c28c73ac242ec8bd2571902b8e93f",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":123},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fc9621e7a3b84f1885da435c82e87437",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":123},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 关于",
                              "target":{
                                "targetType":"page",
                                "url":"关于.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/关于/u42.png"}},
{
                  "id":"fd7cff7fe0c74f6c96299833c169b399",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":153},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"32e4a37dfa2b48558f54f500dfbeaed7",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":153},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 客服电话",
                              "target":{
                                "targetType":"page",
                                "url":"客服电话.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u53.png"}},
{
                  "id":"248852e8d48b4cd29ac23888b1210278",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":31},
                    "size":{
                      "width":100,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e09978a2db214a468b7b7fb6b2601520",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":31},
                        "size":{
                          "width":100,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 工单设置",
                              "target":{
                                "targetType":"page",
                                "url":"工单设置.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/关于/u36.png"}},
{
                  "id":"af1bf4773b73457ea2bd14e320ff5955",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":62},
                    "size":{
                      "width":100,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e144648683414ffc923e2a1dc7810271",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":62},
                        "size":{
                          "width":100,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 积分说明",
                              "target":{
                                "targetType":"page",
                                "url":"积分说明.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/关于/u36.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "289b090006064e5cb6947eb871f6c24e":{
      "scriptId":"u0"},
    "932b83e602964bbaa2af22e3153e224d":{
      "scriptId":"u1"},
    "179b155c8e1e45f9804ba4576128845c":{
      "scriptId":"u2"},
    "d62c5747120c460eaf288041cf355983":{
      "scriptId":"u3"},
    "5e8172fa91c44e30a07d351f42378223":{
      "scriptId":"u4"},
    "53616cbfcf3a436a9681c0c772b0559d":{
      "scriptId":"u5"},
    "6994fc3db9fa4dfd94cd9a1454b5080c":{
      "scriptId":"u6"},
    "5659051362384a1ba2acaaf4a32ffe72":{
      "scriptId":"u7"},
    "56a4f7191487472799b5416242aa392e":{
      "scriptId":"u8"},
    "9ace53e6e3434bc1ac8407553e69a1cc":{
      "scriptId":"u9"},
    "422659f4d31c47349ec4736bfb53f5bf":{
      "scriptId":"u10"},
    "3640b7182860495786c0a4f071a3567b":{
      "scriptId":"u11"},
    "c845b9ef90c6460db1962191e9ca11b4":{
      "scriptId":"u12"},
    "0cde32b6d4fe4fafaad006e742e77232":{
      "scriptId":"u13"},
    "86e1d5f13b4646f99c2078ae24818fc6":{
      "scriptId":"u14"},
    "fb2cf3b747d24b868d45e5c9d91b4ee1":{
      "scriptId":"u15"},
    "ec9165718af346868f6628f064f90a9a":{
      "scriptId":"u16"},
    "ca35eca00e7841ad95b99befe1c83668":{
      "scriptId":"u17"},
    "a0ce6e96446e47e3b32eae9e14bb9143":{
      "scriptId":"u18"},
    "c26fe067bae048b49e3dc1ad0430ff9e":{
      "scriptId":"u19"},
    "1f8109a921f2412db2af064ceef41d4d":{
      "scriptId":"u20"},
    "2ca88ab9787442ec875184fd016d86f9":{
      "scriptId":"u21"},
    "62f916afe5a14981aa4622682f3fcc58":{
      "scriptId":"u22"},
    "09919cb0bcc34580a1ec4e1c2f161ecb":{
      "scriptId":"u23"},
    "9f3e3c6f0239484391d3379002c4c66b":{
      "scriptId":"u24"},
    "8ed9b33ac6cb4109ba57e96f092a13c6":{
      "scriptId":"u25"},
    "0fe47356d93f49ac92113ac281d5d338":{
      "scriptId":"u26"},
    "228408854804433ca23551b5789b4616":{
      "scriptId":"u27"},
    "f7f87a56ad254344937ec4643ebcaef7":{
      "scriptId":"u28"},
    "42a587e445f14db298b004aa8fc4d004":{
      "scriptId":"u29"},
    "e8c9eceb6be847af882b48344f9f3073":{
      "scriptId":"u30"},
    "5b26e9d56d424390ac53fb85ce42e3b3":{
      "scriptId":"u31"},
    "2259872064ad4913b306a797c7585646":{
      "scriptId":"u32"},
    "a130c0507ecb4cf0b81debf87b48a17b":{
      "scriptId":"u33"},
    "9cb11408a24f46968d0fac9553b56cf2":{
      "scriptId":"u34"},
    "5711d25a531f481cba5b0fa62848107b":{
      "scriptId":"u35"},
    "acad0bcf8850470b90c4f5e372560487":{
      "scriptId":"u36"},
    "4f29786e902d4360b9799952048a1433":{
      "scriptId":"u37"},
    "f74f9ddc432f4308b1629ec374423530":{
      "scriptId":"u38"},
    "248852e8d48b4cd29ac23888b1210278":{
      "scriptId":"u39"},
    "e09978a2db214a468b7b7fb6b2601520":{
      "scriptId":"u40"},
    "af1bf4773b73457ea2bd14e320ff5955":{
      "scriptId":"u41"},
    "e144648683414ffc923e2a1dc7810271":{
      "scriptId":"u42"},
    "f1c48339bf644c74abef68eb582e599b":{
      "scriptId":"u43"},
    "fea88d8ca8064501bdebce9136e697c9":{
      "scriptId":"u44"},
    "9c3c28c73ac242ec8bd2571902b8e93f":{
      "scriptId":"u45"},
    "fc9621e7a3b84f1885da435c82e87437":{
      "scriptId":"u46"},
    "fd7cff7fe0c74f6c96299833c169b399":{
      "scriptId":"u47"},
    "32e4a37dfa2b48558f54f500dfbeaed7":{
      "scriptId":"u48"}}});