$axure.loadCurrentPage({
  "url":"detail.html",
  "generationDate":new Date(1425627274745.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a83e03c5bc8f4ea1bf5bf732c483874d",
    "type":"Axure:Page",
    "name":"detail",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e696b22a92dc4c93b8b5b7fd1d2bbdcf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fbd1fef1542442faca49d13f896592f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/slide/u0.png"}},
{
          "id":"5a2da899543b433c917685bc926553da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fa975cdd6ac414b922df13f35af527a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/signup/u2.png"}},
{
          "id":"bd83ebb5ab2344acb024d6b19d99ce24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":16,
              "y":15},
            "size":{
              "width":30,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aec51975b444480be5294eb0045334d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":16,
                  "y":15},
                "size":{
                  "width":30,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/signup/u4.png"}},
{
          "id":"848fb75b09fe43debbf967456433958b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":10,
              "y":60},
            "size":{
              "width":160,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afcd7cd2e2ef42708c14d18b7954bca5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":10,
                  "y":60},
                "size":{
                  "width":160,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/u6.png"}},
{
          "id":"8c5c16881aae486bb1ec412eadafc8d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":170,
              "y":60},
            "size":{
              "width":160,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f2c11e373094b24a734a121119f3c46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":170,
                  "y":60},
                "size":{
                  "width":160,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/u8.png"}},
{
          "id":"a125e65b90984f8db2021bdd479a6f50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":24,
              "y":123},
            "size":{
              "width":82,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1016c86d2d1841619f11b47d8704addf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":24,
                  "y":123},
                "size":{
                  "width":82,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/u10.png"}},
{
          "id":"e3e1e7cb174147daa6c65f879939b331",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "location":{
              "x":118,
              "y":125},
            "size":{
              "width":106,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ddac3510f624d519931497e400d98de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "location":{
                  "x":118,
                  "y":125},
                "size":{
                  "width":106,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2feb8484a744f059d6bc529dd705c59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":216,
              "y":131},
            "size":{
              "width":63,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7f3aba105934b698ebea30c76cb9c8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":216,
                  "y":131},
                "size":{
                  "width":63,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ff2fb708d6a41fabd773d65d84fdf4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":156},
            "size":{
              "width":88,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d11768853af24743bbea8126dfaccd64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":156},
                "size":{
                  "width":88,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0b25b116a044080b5ef1f306a800b49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":175},
            "size":{
              "width":93,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"782633bf5e734d5085819362b49bcef7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":175},
                "size":{
                  "width":93,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33034cf6f2ae4068afb62d6ddaa523b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":24,
              "y":210},
            "size":{
              "width":82,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ab5e506f56246bf8334b014d953e152",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":24,
                  "y":210},
                "size":{
                  "width":82,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/u10.png"}},
{
          "id":"4bfaf4b5413940db83a0e83d61422506",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "location":{
              "x":118,
              "y":212},
            "size":{
              "width":106,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a21821c6ff604f4a964e3cf78150f582",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "location":{
                  "x":118,
                  "y":212},
                "size":{
                  "width":106,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0623e667fbb346a5ae286adfe816f8b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":216,
              "y":218},
            "size":{
              "width":63,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8372f8864004e19b19cef1c3544c0db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":216,
                  "y":218},
                "size":{
                  "width":63,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd36bf3a70c14d53b236e325603e4306",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":243},
            "size":{
              "width":88,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3d8d7352f2548cabc30924f7b336746",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":243},
                "size":{
                  "width":88,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be686d1311c34471b97e264385f85efe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":262},
            "size":{
              "width":93,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63ed76a32f114a9ab0812447320ed9d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":262},
                "size":{
                  "width":93,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0c0cf4371244cd9af005c902988565b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":24,
              "y":300},
            "size":{
              "width":82,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa6bdf39771d45e296f9c64b70c84767",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":24,
                  "y":300},
                "size":{
                  "width":82,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/u10.png"}},
{
          "id":"6f7a77c4b05b469aa0fe2cc1fac8a5fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "location":{
              "x":118,
              "y":302},
            "size":{
              "width":106,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a896396694443e2826f020714985c98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "location":{
                  "x":118,
                  "y":302},
                "size":{
                  "width":106,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"649f845e0cc847caa843d72ee003ddae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":216,
              "y":308},
            "size":{
              "width":63,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06aedbb6a5d34b8fbceef234e1fc0e4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":216,
                  "y":308},
                "size":{
                  "width":63,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98bb9f827b7d41a4a383f8302b8d8e2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":333},
            "size":{
              "width":88,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a9ed95f2a63408e862b75668850fc8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":333},
                "size":{
                  "width":88,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37c24689d1eb46a2bd14ce1ff67cfac7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":352},
            "size":{
              "width":93,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dfd6199ebfd41bb95c79fb7d1c7cfaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":352},
                "size":{
                  "width":93,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b08205af4664e8285066f2d26705341",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":24,
              "y":390},
            "size":{
              "width":82,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c9a35b135cf43f8b1d7b32abe31aad5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":24,
                  "y":390},
                "size":{
                  "width":82,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/u10.png"}},
{
          "id":"9165e78ee86b474e941cad0487968e29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "location":{
              "x":118,
              "y":392},
            "size":{
              "width":106,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc8f0186ec604d47a734e6bcd9f92ada",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "location":{
                  "x":118,
                  "y":392},
                "size":{
                  "width":106,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6abe2082afda4eb39e8e3a966a600e92",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":216,
              "y":398},
            "size":{
              "width":63,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"080097327669423c905433c87588ee33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":216,
                  "y":398},
                "size":{
                  "width":63,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6585a67d5bce47058dec792c52094c0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":423},
            "size":{
              "width":88,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"951ab22ddbad4cfeb7c9d8f9b63fcce5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":423},
                "size":{
                  "width":88,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a14fb1a320cb4c149d8da34a7eae62d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":442},
            "size":{
              "width":93,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b69da43d4a5481ca0ac6b1bc4836a2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":442},
                "size":{
                  "width":93,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91f6ac471ed34ac299646e34441df4bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":24,
              "y":480},
            "size":{
              "width":82,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"094ed7d51f6b492f819285d8dbe76f19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":24,
                  "y":480},
                "size":{
                  "width":82,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/u10.png"}},
{
          "id":"0626a6c4cabf4bba9c86124cfc82546d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "location":{
              "x":118,
              "y":482},
            "size":{
              "width":106,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe6da8e6389e45a59c35f494f90a18b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "location":{
                  "x":118,
                  "y":482},
                "size":{
                  "width":106,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9368291b9d554d33b148c8970d050a26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":216,
              "y":488},
            "size":{
              "width":63,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cec8926442dc498c9137e88794ace573",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":216,
                  "y":488},
                "size":{
                  "width":63,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa351094a8394de4a9ecee64c1b827ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":513},
            "size":{
              "width":88,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abeddf00f17e49988e335d61b8e14414",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":513},
                "size":{
                  "width":88,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eac49f1a0ff34ee69fa23112ad7d7d11",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":58,
              "y":18},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8da492f1c2346509137292fd25b1413",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":58,
                  "y":18},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u8.png"}},
{
          "id":"e00338f79a2a4c218863fcffd23c9a0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":532},
            "size":{
              "width":93,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d6ab931a31c435fba7c84e1cbefd607",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":532},
                "size":{
                  "width":93,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a3f4f0899d74a05b5c786dc529a60c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xC4000000},
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0b5a50a5ade41f2927e99c7bb08512f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xC4000000},
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail/u62.png"}},
{
          "id":"5e1d4230117d4133875cc8cdae526c6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":24,
              "y":140},
            "size":{
              "width":286,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af84c7e2138f416e9b1a4bbcf561cda8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":24,
                  "y":140},
                "size":{
                  "width":286,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail/u64.png"}},
{
          "id":"95f6b9f1f6d145aea3bcc3e1ce1ea84a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":294,
              "y":125},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1999515d74924abc965354399ecdfbc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":294,
                  "y":125},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 success",
                      "target":{
                        "targetType":"page",
                        "url":"success.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/detail/u66.png"}},
{
          "id":"5ff2e100d2ec47cb86b9ee9a844c30e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":24,
              "y":370},
            "size":{
              "width":286,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e6664f1134744409d2744643063b837",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":24,
                  "y":370},
                "size":{
                  "width":286,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail/u68.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e696b22a92dc4c93b8b5b7fd1d2bbdcf":{
      "scriptId":"u0"},
    "1fbd1fef1542442faca49d13f896592f":{
      "scriptId":"u1"},
    "5a2da899543b433c917685bc926553da":{
      "scriptId":"u2"},
    "3fa975cdd6ac414b922df13f35af527a":{
      "scriptId":"u3"},
    "bd83ebb5ab2344acb024d6b19d99ce24":{
      "scriptId":"u4"},
    "7aec51975b444480be5294eb0045334d":{
      "scriptId":"u5"},
    "848fb75b09fe43debbf967456433958b":{
      "scriptId":"u6"},
    "afcd7cd2e2ef42708c14d18b7954bca5":{
      "scriptId":"u7"},
    "8c5c16881aae486bb1ec412eadafc8d9":{
      "scriptId":"u8"},
    "0f2c11e373094b24a734a121119f3c46":{
      "scriptId":"u9"},
    "a125e65b90984f8db2021bdd479a6f50":{
      "scriptId":"u10"},
    "1016c86d2d1841619f11b47d8704addf":{
      "scriptId":"u11"},
    "e3e1e7cb174147daa6c65f879939b331":{
      "scriptId":"u12"},
    "4ddac3510f624d519931497e400d98de":{
      "scriptId":"u13"},
    "a2feb8484a744f059d6bc529dd705c59":{
      "scriptId":"u14"},
    "c7f3aba105934b698ebea30c76cb9c8e":{
      "scriptId":"u15"},
    "2ff2fb708d6a41fabd773d65d84fdf4d":{
      "scriptId":"u16"},
    "d11768853af24743bbea8126dfaccd64":{
      "scriptId":"u17"},
    "f0b25b116a044080b5ef1f306a800b49":{
      "scriptId":"u18"},
    "782633bf5e734d5085819362b49bcef7":{
      "scriptId":"u19"},
    "33034cf6f2ae4068afb62d6ddaa523b0":{
      "scriptId":"u20"},
    "4ab5e506f56246bf8334b014d953e152":{
      "scriptId":"u21"},
    "4bfaf4b5413940db83a0e83d61422506":{
      "scriptId":"u22"},
    "a21821c6ff604f4a964e3cf78150f582":{
      "scriptId":"u23"},
    "0623e667fbb346a5ae286adfe816f8b6":{
      "scriptId":"u24"},
    "e8372f8864004e19b19cef1c3544c0db":{
      "scriptId":"u25"},
    "cd36bf3a70c14d53b236e325603e4306":{
      "scriptId":"u26"},
    "e3d8d7352f2548cabc30924f7b336746":{
      "scriptId":"u27"},
    "be686d1311c34471b97e264385f85efe":{
      "scriptId":"u28"},
    "63ed76a32f114a9ab0812447320ed9d0":{
      "scriptId":"u29"},
    "e0c0cf4371244cd9af005c902988565b":{
      "scriptId":"u30"},
    "fa6bdf39771d45e296f9c64b70c84767":{
      "scriptId":"u31"},
    "6f7a77c4b05b469aa0fe2cc1fac8a5fa":{
      "scriptId":"u32"},
    "9a896396694443e2826f020714985c98":{
      "scriptId":"u33"},
    "649f845e0cc847caa843d72ee003ddae":{
      "scriptId":"u34"},
    "06aedbb6a5d34b8fbceef234e1fc0e4c":{
      "scriptId":"u35"},
    "98bb9f827b7d41a4a383f8302b8d8e2e":{
      "scriptId":"u36"},
    "1a9ed95f2a63408e862b75668850fc8c":{
      "scriptId":"u37"},
    "37c24689d1eb46a2bd14ce1ff67cfac7":{
      "scriptId":"u38"},
    "5dfd6199ebfd41bb95c79fb7d1c7cfaa":{
      "scriptId":"u39"},
    "1b08205af4664e8285066f2d26705341":{
      "scriptId":"u40"},
    "9c9a35b135cf43f8b1d7b32abe31aad5":{
      "scriptId":"u41"},
    "9165e78ee86b474e941cad0487968e29":{
      "scriptId":"u42"},
    "cc8f0186ec604d47a734e6bcd9f92ada":{
      "scriptId":"u43"},
    "6abe2082afda4eb39e8e3a966a600e92":{
      "scriptId":"u44"},
    "080097327669423c905433c87588ee33":{
      "scriptId":"u45"},
    "6585a67d5bce47058dec792c52094c0f":{
      "scriptId":"u46"},
    "951ab22ddbad4cfeb7c9d8f9b63fcce5":{
      "scriptId":"u47"},
    "a14fb1a320cb4c149d8da34a7eae62d2":{
      "scriptId":"u48"},
    "9b69da43d4a5481ca0ac6b1bc4836a2f":{
      "scriptId":"u49"},
    "91f6ac471ed34ac299646e34441df4bd":{
      "scriptId":"u50"},
    "094ed7d51f6b492f819285d8dbe76f19":{
      "scriptId":"u51"},
    "0626a6c4cabf4bba9c86124cfc82546d":{
      "scriptId":"u52"},
    "fe6da8e6389e45a59c35f494f90a18b5":{
      "scriptId":"u53"},
    "9368291b9d554d33b148c8970d050a26":{
      "scriptId":"u54"},
    "cec8926442dc498c9137e88794ace573":{
      "scriptId":"u55"},
    "fa351094a8394de4a9ecee64c1b827ca":{
      "scriptId":"u56"},
    "abeddf00f17e49988e335d61b8e14414":{
      "scriptId":"u57"},
    "eac49f1a0ff34ee69fa23112ad7d7d11":{
      "scriptId":"u58"},
    "a8da492f1c2346509137292fd25b1413":{
      "scriptId":"u59"},
    "e00338f79a2a4c218863fcffd23c9a0d":{
      "scriptId":"u60"},
    "8d6ab931a31c435fba7c84e1cbefd607":{
      "scriptId":"u61"},
    "8a3f4f0899d74a05b5c786dc529a60c7":{
      "scriptId":"u62"},
    "a0b5a50a5ade41f2927e99c7bb08512f":{
      "scriptId":"u63"},
    "5e1d4230117d4133875cc8cdae526c6d":{
      "scriptId":"u64"},
    "af84c7e2138f416e9b1a4bbcf561cda8":{
      "scriptId":"u65"},
    "95f6b9f1f6d145aea3bcc3e1ce1ea84a":{
      "scriptId":"u66"},
    "1999515d74924abc965354399ecdfbc9":{
      "scriptId":"u67"},
    "5ff2e100d2ec47cb86b9ee9a844c30e0":{
      "scriptId":"u68"},
    "8e6664f1134744409d2744643063b837":{
      "scriptId":"u69"}}});