$axure.loadCurrentPage({
  "url":"detail_1.html",
  "generationDate":new Date(1425627274941.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4f2e33831ba746a797ca89a4c34e4aba",
    "type":"Axure:Page",
    "name":"detail",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"88251abab2274ae699d02fc0f1de30bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef25df7b3ad74a9998fd4474ade44408",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/slide/u0.png"}},
{
          "id":"809b3a969f7c42db87186cbcd15e7917",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca86942eba0b428281c59756d24cf9c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/signup/u2.png"}},
{
          "id":"3d8f8a725ab34b79bb01c10c3ec25982",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":16,
              "y":15},
            "size":{
              "width":30,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"deb76e8119924f63a9d93682adf8f1df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":16,
                  "y":15},
                "size":{
                  "width":30,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/signup/u4.png"}},
{
          "id":"0ceb42c7013c440ea7b378e80f7a01fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":10,
              "y":60},
            "size":{
              "width":160,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96dfe2a01517462bb97541ef3ba9d8e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":10,
                  "y":60},
                "size":{
                  "width":160,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/u8.png"}},
{
          "id":"ae6abf6aa8214fee9ea948a32c7d0ff5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":170,
              "y":60},
            "size":{
              "width":160,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a428ba6d202346019a83edbca1e9135a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":170,
                  "y":60},
                "size":{
                  "width":160,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/u6.png"}},
{
          "id":"e90e70fbcf244cfbb76b7a022d42e297",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":24,
              "y":123},
            "size":{
              "width":82,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66b039401d294fdc989080db1ba3432a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":24,
                  "y":123},
                "size":{
                  "width":82,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/u10.png"}},
{
          "id":"c155b5afb2f54295964d15a77109a428",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "location":{
              "x":118,
              "y":125},
            "size":{
              "width":106,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c78fd1a54f54593a319670facb48ac9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "location":{
                  "x":118,
                  "y":125},
                "size":{
                  "width":106,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"435d7c735f934cdfa85f4c266f4b0fb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":216,
              "y":131},
            "size":{
              "width":63,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b64cea5d769847c691e0f3a57cfadc3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":216,
                  "y":131},
                "size":{
                  "width":63,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"506986caef4341a2b3e256b78410b02b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":156},
            "size":{
              "width":88,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3f7adb801044fb9aee1fc1d79099450",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":156},
                "size":{
                  "width":88,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0558b4441ef1488bbd9985e67680671e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":175},
            "size":{
              "width":131,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"264147eb2ed74a84bd84914bf4d88d12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":175},
                "size":{
                  "width":131,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86ac8b333ee0412985974a12b8640289",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":24,
              "y":210},
            "size":{
              "width":82,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"143e3b1fa0d1439d939269a7de0f3573",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":24,
                  "y":210},
                "size":{
                  "width":82,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/u10.png"}},
{
          "id":"adaa4cd1a4c94ae1b5584bb80b6f7a8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "location":{
              "x":118,
              "y":212},
            "size":{
              "width":106,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"101d0647654047c08c3d486856e16743",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "location":{
                  "x":118,
                  "y":212},
                "size":{
                  "width":106,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e08f2b2e826548a0a3e63ab5655d18cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":216,
              "y":218},
            "size":{
              "width":63,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02467878b730450e97be76fc971e0bff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":216,
                  "y":218},
                "size":{
                  "width":63,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9a978a872ba4787b55234c5d896d359",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":243},
            "size":{
              "width":88,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e57136ecf7c4bd8963b1cbee40b74b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":243},
                "size":{
                  "width":88,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d96e658d77d9421b9b4d3c1760b7fa46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":262},
            "size":{
              "width":131,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aa1c3f7de93461e995c05c1e84bd3f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":262},
                "size":{
                  "width":131,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"113a3bd737bf41fdb99a2c75cbec0a39",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":24,
              "y":300},
            "size":{
              "width":82,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"995d89541688413caf13e0c672df53ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":24,
                  "y":300},
                "size":{
                  "width":82,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/u10.png"}},
{
          "id":"08ffc3b330414c30b5a37c65735e9993",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "location":{
              "x":118,
              "y":302},
            "size":{
              "width":106,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98e8ae4b47374ddaafb518ea4919a963",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "location":{
                  "x":118,
                  "y":302},
                "size":{
                  "width":106,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f846e3e611c44b88be8fb447368e8d27",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":216,
              "y":308},
            "size":{
              "width":63,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37882802f1c1459e97ca43a9c130527e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":216,
                  "y":308},
                "size":{
                  "width":63,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"700a1c9d2ca24925b294e675de3fecc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":333},
            "size":{
              "width":88,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcfbe22fb7b34dd5904a74f180c6744e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":333},
                "size":{
                  "width":88,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b93efe4705544a9bbe2a5e335d94d91b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":352},
            "size":{
              "width":131,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ceb059729b564d33b3f7b26c20bb5978",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":352},
                "size":{
                  "width":131,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f038941452f94160ad148eb2bbe0fd4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":24,
              "y":390},
            "size":{
              "width":82,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9003d6d60b6e4aa6b1025b3b244f4621",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":24,
                  "y":390},
                "size":{
                  "width":82,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/u10.png"}},
{
          "id":"2eaa50b8c16847b6ae267ecce6cd5a64",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "location":{
              "x":118,
              "y":392},
            "size":{
              "width":106,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a50638889cb4b31b58660ded757552c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "location":{
                  "x":118,
                  "y":392},
                "size":{
                  "width":106,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb8de896fbf74b259ad5ceddbd183c25",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":216,
              "y":398},
            "size":{
              "width":63,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83a060b2746744c480d9d2e416899af1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":216,
                  "y":398},
                "size":{
                  "width":63,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"611811fa527e4280b76b4a4899db3b1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":423},
            "size":{
              "width":88,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5f07be612e9470dbd024438812fa0aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":423},
                "size":{
                  "width":88,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f02961c1f49540809706c1dfece5d978",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":442},
            "size":{
              "width":131,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2d3adf4f1fe4e71b02fd301466dcba3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":442},
                "size":{
                  "width":131,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44b989d7788f41448cb6fa3524341f6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":24,
              "y":480},
            "size":{
              "width":82,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94c5fdfb35f949519ecd65a6fad3b4ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":24,
                  "y":480},
                "size":{
                  "width":82,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/u10.png"}},
{
          "id":"12f7411b9dfe40a38b1a398ee1d4fcd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "location":{
              "x":118,
              "y":482},
            "size":{
              "width":106,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cb43e73b38b4053974405d7eb0bbad9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "location":{
                  "x":118,
                  "y":482},
                "size":{
                  "width":106,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26a68b4867034f2ca6fafb26fba07a2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":216,
              "y":488},
            "size":{
              "width":63,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a3a965228334e12871e51aaa3374a33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":216,
                  "y":488},
                "size":{
                  "width":63,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b842bc88020b47f9ad02dc93f6a7927a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":513},
            "size":{
              "width":88,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bf2c217f31d4a0d8b3b4139798ab193",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":513},
                "size":{
                  "width":88,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdc2b20f60bc40efb2e1f367593e5468",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":532},
            "size":{
              "width":131,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfb89cc1a4f748a480fc45bef2d461b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":532},
                "size":{
                  "width":131,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a242aabef2e416f92848cc4eb9a3eac",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":58,
              "y":18},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b66d11b0a68f4aa5884e2ff9cc369512",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":58,
                  "y":18},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u8.png"}},
{
          "id":"7954bc9162b446439846369a06b68a96",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xC4000000},
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43674dcfd7b7444a99043b9e113bae11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xC4000000},
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail/u62.png"}},
{
          "id":"011e3a97b0f2418f8ab165165cbe5d25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":24,
              "y":85},
            "size":{
              "width":286,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d4f6c65d2984edc85fa089944c6910d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":24,
                  "y":85},
                "size":{
                  "width":286,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail/u64.png"}},
{
          "id":"df3a6b599fb646c3b7344a3670a29f5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":294,
              "y":70},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0923950f5e90443185865d8080788b9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":294,
                  "y":70},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 fail",
                      "target":{
                        "targetType":"page",
                        "url":"fail.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/detail/u66.png"}},
{
          "id":"e1cdea33af23450db0c10b2dad226261",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":24,
              "y":351},
            "size":{
              "width":286,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0fda49be2bf473f91c814fd9dbfe667",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":24,
                  "y":351},
                "size":{
                  "width":286,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail_1/u68.png"}},
{
          "id":"eda59bc4f62545378dfd5b7d1625426a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "location":{
              "x":24,
              "y":315},
            "size":{
              "width":286,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"970ad0561448402894f1ad70c94c20ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "location":{
                  "x":24,
                  "y":315},
                "size":{
                  "width":286,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail_1/u70.png"}},
{
          "id":"04ffcef293b84a03a05480d314aad661",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":24,
              "y":433},
            "size":{
              "width":286,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4919b0edcff44c12882ebc5120cdbdee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":24,
                  "y":433},
                "size":{
                  "width":286,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail_1/u68.png"}},
{
          "id":"7ffe81946c4144fd9b6aa2fb6f58c871",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "location":{
              "x":24,
              "y":397},
            "size":{
              "width":286,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e01416659a7f4be9b4fa2b2b0f8fdbe0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "location":{
                  "x":24,
                  "y":397},
                "size":{
                  "width":286,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail_1/u70.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "88251abab2274ae699d02fc0f1de30bb":{
      "scriptId":"u0"},
    "ef25df7b3ad74a9998fd4474ade44408":{
      "scriptId":"u1"},
    "809b3a969f7c42db87186cbcd15e7917":{
      "scriptId":"u2"},
    "ca86942eba0b428281c59756d24cf9c2":{
      "scriptId":"u3"},
    "3d8f8a725ab34b79bb01c10c3ec25982":{
      "scriptId":"u4"},
    "deb76e8119924f63a9d93682adf8f1df":{
      "scriptId":"u5"},
    "0ceb42c7013c440ea7b378e80f7a01fe":{
      "scriptId":"u6"},
    "96dfe2a01517462bb97541ef3ba9d8e4":{
      "scriptId":"u7"},
    "ae6abf6aa8214fee9ea948a32c7d0ff5":{
      "scriptId":"u8"},
    "a428ba6d202346019a83edbca1e9135a":{
      "scriptId":"u9"},
    "e90e70fbcf244cfbb76b7a022d42e297":{
      "scriptId":"u10"},
    "66b039401d294fdc989080db1ba3432a":{
      "scriptId":"u11"},
    "c155b5afb2f54295964d15a77109a428":{
      "scriptId":"u12"},
    "1c78fd1a54f54593a319670facb48ac9":{
      "scriptId":"u13"},
    "435d7c735f934cdfa85f4c266f4b0fb5":{
      "scriptId":"u14"},
    "b64cea5d769847c691e0f3a57cfadc3c":{
      "scriptId":"u15"},
    "506986caef4341a2b3e256b78410b02b":{
      "scriptId":"u16"},
    "d3f7adb801044fb9aee1fc1d79099450":{
      "scriptId":"u17"},
    "0558b4441ef1488bbd9985e67680671e":{
      "scriptId":"u18"},
    "264147eb2ed74a84bd84914bf4d88d12":{
      "scriptId":"u19"},
    "86ac8b333ee0412985974a12b8640289":{
      "scriptId":"u20"},
    "143e3b1fa0d1439d939269a7de0f3573":{
      "scriptId":"u21"},
    "adaa4cd1a4c94ae1b5584bb80b6f7a8b":{
      "scriptId":"u22"},
    "101d0647654047c08c3d486856e16743":{
      "scriptId":"u23"},
    "e08f2b2e826548a0a3e63ab5655d18cd":{
      "scriptId":"u24"},
    "02467878b730450e97be76fc971e0bff":{
      "scriptId":"u25"},
    "b9a978a872ba4787b55234c5d896d359":{
      "scriptId":"u26"},
    "0e57136ecf7c4bd8963b1cbee40b74b6":{
      "scriptId":"u27"},
    "d96e658d77d9421b9b4d3c1760b7fa46":{
      "scriptId":"u28"},
    "0aa1c3f7de93461e995c05c1e84bd3f8":{
      "scriptId":"u29"},
    "113a3bd737bf41fdb99a2c75cbec0a39":{
      "scriptId":"u30"},
    "995d89541688413caf13e0c672df53ea":{
      "scriptId":"u31"},
    "08ffc3b330414c30b5a37c65735e9993":{
      "scriptId":"u32"},
    "98e8ae4b47374ddaafb518ea4919a963":{
      "scriptId":"u33"},
    "f846e3e611c44b88be8fb447368e8d27":{
      "scriptId":"u34"},
    "37882802f1c1459e97ca43a9c130527e":{
      "scriptId":"u35"},
    "700a1c9d2ca24925b294e675de3fecc5":{
      "scriptId":"u36"},
    "fcfbe22fb7b34dd5904a74f180c6744e":{
      "scriptId":"u37"},
    "b93efe4705544a9bbe2a5e335d94d91b":{
      "scriptId":"u38"},
    "ceb059729b564d33b3f7b26c20bb5978":{
      "scriptId":"u39"},
    "f038941452f94160ad148eb2bbe0fd4c":{
      "scriptId":"u40"},
    "9003d6d60b6e4aa6b1025b3b244f4621":{
      "scriptId":"u41"},
    "2eaa50b8c16847b6ae267ecce6cd5a64":{
      "scriptId":"u42"},
    "7a50638889cb4b31b58660ded757552c":{
      "scriptId":"u43"},
    "eb8de896fbf74b259ad5ceddbd183c25":{
      "scriptId":"u44"},
    "83a060b2746744c480d9d2e416899af1":{
      "scriptId":"u45"},
    "611811fa527e4280b76b4a4899db3b1f":{
      "scriptId":"u46"},
    "d5f07be612e9470dbd024438812fa0aa":{
      "scriptId":"u47"},
    "f02961c1f49540809706c1dfece5d978":{
      "scriptId":"u48"},
    "c2d3adf4f1fe4e71b02fd301466dcba3":{
      "scriptId":"u49"},
    "44b989d7788f41448cb6fa3524341f6c":{
      "scriptId":"u50"},
    "94c5fdfb35f949519ecd65a6fad3b4ae":{
      "scriptId":"u51"},
    "12f7411b9dfe40a38b1a398ee1d4fcd0":{
      "scriptId":"u52"},
    "0cb43e73b38b4053974405d7eb0bbad9":{
      "scriptId":"u53"},
    "26a68b4867034f2ca6fafb26fba07a2d":{
      "scriptId":"u54"},
    "0a3a965228334e12871e51aaa3374a33":{
      "scriptId":"u55"},
    "b842bc88020b47f9ad02dc93f6a7927a":{
      "scriptId":"u56"},
    "1bf2c217f31d4a0d8b3b4139798ab193":{
      "scriptId":"u57"},
    "bdc2b20f60bc40efb2e1f367593e5468":{
      "scriptId":"u58"},
    "dfb89cc1a4f748a480fc45bef2d461b6":{
      "scriptId":"u59"},
    "7a242aabef2e416f92848cc4eb9a3eac":{
      "scriptId":"u60"},
    "b66d11b0a68f4aa5884e2ff9cc369512":{
      "scriptId":"u61"},
    "7954bc9162b446439846369a06b68a96":{
      "scriptId":"u62"},
    "43674dcfd7b7444a99043b9e113bae11":{
      "scriptId":"u63"},
    "011e3a97b0f2418f8ab165165cbe5d25":{
      "scriptId":"u64"},
    "5d4f6c65d2984edc85fa089944c6910d":{
      "scriptId":"u65"},
    "df3a6b599fb646c3b7344a3670a29f5b":{
      "scriptId":"u66"},
    "0923950f5e90443185865d8080788b9b":{
      "scriptId":"u67"},
    "e1cdea33af23450db0c10b2dad226261":{
      "scriptId":"u68"},
    "c0fda49be2bf473f91c814fd9dbfe667":{
      "scriptId":"u69"},
    "eda59bc4f62545378dfd5b7d1625426a":{
      "scriptId":"u70"},
    "970ad0561448402894f1ad70c94c20ae":{
      "scriptId":"u71"},
    "04ffcef293b84a03a05480d314aad661":{
      "scriptId":"u72"},
    "4919b0edcff44c12882ebc5120cdbdee":{
      "scriptId":"u73"},
    "7ffe81946c4144fd9b6aa2fb6f58c871":{
      "scriptId":"u74"},
    "e01416659a7f4be9b4fa2b2b0f8fdbe0":{
      "scriptId":"u75"}}});