$axure.loadCurrentPage({
  "url":"signin.html",
  "generationDate":new Date(1425627273205.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cbf8c7146d744428bb6de474e3c5652a",
    "type":"Axure:Page",
    "name":"signIn",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"537a44956e044ea699e42208b74e2fd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"590e26e808c440459e67a640678fc718",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/slide/u0.png"}},
{
          "id":"6d011c0b41ed49c7b4cdf09bd0db8470",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":110,
              "y":80},
            "size":{
              "width":120,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18f043692372498fba7f50e50a1ba2ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":110,
                  "y":80},
                "size":{
                  "width":120,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/signin/u2.png"}},
{
          "id":"acc707d357674f8a8b29d3ef12988d52",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":40,
              "y":240},
            "size":{
              "width":260,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d0971eddf154319903d5bede5dd9c65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":240},
                "size":{
                  "width":260,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/signin/u4.png"}},
{
          "id":"1277e7fad16f4866bb308a4be1c0e7a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":40,
              "y":300},
            "size":{
              "width":260,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"440daee5cfb4475c936beb5e737f4926",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":300},
                "size":{
                  "width":260,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/signin/u4.png"}},
{
          "id":"9fe1928c4ab6440785ce5da43a4610bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":40,
              "y":370},
            "size":{
              "width":260,
              "height":50},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11d307e41942475e812e16428e02f185",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":370},
                "size":{
                  "width":260,
                  "height":50},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 home",
                      "target":{
                        "targetType":"page",
                        "url":"home_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/signin/u8.png"}},
{
          "id":"62bd461df0b24baaa44c66e7669ad601",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":40,
              "y":435},
            "size":{
              "width":110,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bdbb49259d049d889d7f7c1eaedeb35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":40,
                  "y":435},
                "size":{
                  "width":110,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 getPassword",
                      "target":{
                        "targetType":"page",
                        "url":"getpassword.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53a4db375cc34ac7bf923895aff50777",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"right",
            "location":{
              "x":190,
              "y":435},
            "size":{
              "width":110,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecb6654f8c5c47f4811a65361a7e86cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"right",
                "location":{
                  "x":190,
                  "y":435},
                "size":{
                  "width":110,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 signUp",
                      "target":{
                        "targetType":"page",
                        "url":"signup.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "537a44956e044ea699e42208b74e2fd0":{
      "scriptId":"u0"},
    "590e26e808c440459e67a640678fc718":{
      "scriptId":"u1"},
    "6d011c0b41ed49c7b4cdf09bd0db8470":{
      "scriptId":"u2"},
    "18f043692372498fba7f50e50a1ba2ef":{
      "scriptId":"u3"},
    "acc707d357674f8a8b29d3ef12988d52":{
      "scriptId":"u4"},
    "6d0971eddf154319903d5bede5dd9c65":{
      "scriptId":"u5"},
    "1277e7fad16f4866bb308a4be1c0e7a4":{
      "scriptId":"u6"},
    "440daee5cfb4475c936beb5e737f4926":{
      "scriptId":"u7"},
    "9fe1928c4ab6440785ce5da43a4610bc":{
      "scriptId":"u8"},
    "11d307e41942475e812e16428e02f185":{
      "scriptId":"u9"},
    "62bd461df0b24baaa44c66e7669ad601":{
      "scriptId":"u10"},
    "4bdbb49259d049d889d7f7c1eaedeb35":{
      "scriptId":"u11"},
    "53a4db375cc34ac7bf923895aff50777":{
      "scriptId":"u12"},
    "ecb6654f8c5c47f4811a65361a7e86cc":{
      "scriptId":"u13"}}});