$axure.loadCurrentPage({
  "url":"index_1.html",
  "generationDate":new Date(1425627273921.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c334aae5e5384090b57aca771312cd3f",
    "type":"Axure:Page",
    "name":"index",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8ddf0dd1b03c46e399117c5dc9bc1b25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c2847a3dc15486eba4666744e69e6f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/slide/u0.png"}},
{
          "id":"b8ace631fa564467a4856039e3e83e43",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b381695e31f34ea1a3b75f622503cea9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/signup/u2.png"}},
{
          "id":"c89ce88ed5a649949e88d5b64b2380af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "location":{
              "x":30,
              "y":87},
            "size":{
              "width":61,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd6a4eedcfe7498b839a7dc9daae0c19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "location":{
                  "x":30,
                  "y":87},
                "size":{
                  "width":61,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc13380d9ca5429996a28bc768af899d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":118},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index_1/u6_line.png"}},
{
          "id":"341e0a9558674834a7fdbc3f926966a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"900",
            "horizontalAlignment":"right",
            "location":{
              "x":275,
              "y":84},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"984d3d792c7c420d830c90f237a03144",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"900",
                "horizontalAlignment":"right",
                "location":{
                  "x":275,
                  "y":84},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 editNickname",
                      "target":{
                        "targetType":"page",
                        "url":"editnickname.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f0266b7b4a54e1da39bd1b3d09caf7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":30,
              "y":140},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c4ff89e38634b6cb9c0c44cf4e45471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":30,
                  "y":140},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cc6be9630044799b7ef66241cf5fef4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":171},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index_1/u6_line.png"}},
{
          "id":"1bc5eb33adff4b92a5302de91577eb6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":30,
              "y":490},
            "size":{
              "width":285,
              "height":50},
            "cornerRadiusTopLeft":"87"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"651cbf32e9474f0ea56aa3e663c9b1aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":30,
                  "y":490},
                "size":{
                  "width":285,
                  "height":50},
                "cornerRadiusTopLeft":"87"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 signln（after）",
                      "target":{
                        "targetType":"page",
                        "url":"signln_after_.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index_1/u12.png"}},
{
          "id":"983f55c4f2ef491d89b466a33443b4f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":16,
              "y":15},
            "size":{
              "width":30,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c702b7b2870e40a89e63311fe26769de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":16,
                  "y":15},
                "size":{
                  "width":30,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/signup/u4.png"}},
{
          "id":"f1e3282618c7477395af9a7f6e69ec74",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":30,
              "y":200},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b08043ca69b74838bb8081933948099f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":30,
                  "y":200},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfcdf4162a36460e85a930d4198e2194",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":231},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index_1/u6_line.png"}},
{
          "id":"0937b8d12b4141c1962d122f7b58b8e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"900",
            "horizontalAlignment":"right",
            "location":{
              "x":275,
              "y":138},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"920caf78dc054bac9ae3dfacb41b2fa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"900",
                "horizontalAlignment":"right",
                "location":{
                  "x":275,
                  "y":138},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 resetPassword",
                      "target":{
                        "targetType":"page",
                        "url":"resetpassword.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d13b6e300b6c4b8299992b941b79abb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"900",
            "horizontalAlignment":"right",
            "location":{
              "x":275,
              "y":191},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb47c8ac0dc94f38a844e0afaa3cfe22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"900",
                "horizontalAlignment":"right",
                "location":{
                  "x":275,
                  "y":191},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (动态面板),<br>(动态面板),<br>切换 (形状),<br>(形状)",
                      "objectsToFades":[{
                          "objectPath":["d9f8a240768841718b2c7396ee63eb45"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["50cc5815d6e94a53ae7e1c0993c538b3"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2a5e0c53a6ba4a258a0bd08017b92743"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["fa5bdc7a2d5f4658ac69229a8f9ab199"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9f8a240768841718b2c7396ee63eb45",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":160,
              "y":212},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 bankAccount",
                      "target":{
                        "targetType":"page",
                        "url":"bankaccount.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"bdf89d33b52b4459af3e5146e425d907",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"50cc5815d6e94a53ae7e1c0993c538b3",
                  "label":"",
                  "parentDynamicPanel":"d9f8a240768841718b2c7396ee63eb45",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"28px",
                    "fontWeight":"900",
                    "size":{
                      "width":170,
                      "height":59}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"16ace0c5459348d79bc06057db940b73",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d9f8a240768841718b2c7396ee63eb45",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"28px",
                        "fontWeight":"900",
                        "size":{
                          "width":170,
                          "height":59}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index_1/u24.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"2a5e0c53a6ba4a258a0bd08017b92743",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":160,
              "y":271},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Pay treasure",
                      "target":{
                        "targetType":"page",
                        "url":"pay_treasure.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"dc59969326cf4937ace8db9ed11a35f5",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fa5bdc7a2d5f4658ac69229a8f9ab199",
                  "label":"",
                  "parentDynamicPanel":"2a5e0c53a6ba4a258a0bd08017b92743",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"28px",
                    "fontWeight":"900",
                    "size":{
                      "width":170,
                      "height":59}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"417652d834764ca5ab8b037e085ee507",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2a5e0c53a6ba4a258a0bd08017b92743",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"28px",
                        "fontWeight":"900",
                        "size":{
                          "width":170,
                          "height":59}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index_1/u24.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"102f43a47cc54d5d916007bbc1770986",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":50,
              "y":18},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d59a64690a6347bcb701f9f9541ff34e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":50,
                  "y":18},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u8.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8ddf0dd1b03c46e399117c5dc9bc1b25":{
      "scriptId":"u0"},
    "4c2847a3dc15486eba4666744e69e6f2":{
      "scriptId":"u1"},
    "b8ace631fa564467a4856039e3e83e43":{
      "scriptId":"u2"},
    "b381695e31f34ea1a3b75f622503cea9":{
      "scriptId":"u3"},
    "c89ce88ed5a649949e88d5b64b2380af":{
      "scriptId":"u4"},
    "bd6a4eedcfe7498b839a7dc9daae0c19":{
      "scriptId":"u5"},
    "fc13380d9ca5429996a28bc768af899d":{
      "scriptId":"u6"},
    "341e0a9558674834a7fdbc3f926966a5":{
      "scriptId":"u7"},
    "984d3d792c7c420d830c90f237a03144":{
      "scriptId":"u8"},
    "5f0266b7b4a54e1da39bd1b3d09caf7c":{
      "scriptId":"u9"},
    "8c4ff89e38634b6cb9c0c44cf4e45471":{
      "scriptId":"u10"},
    "9cc6be9630044799b7ef66241cf5fef4":{
      "scriptId":"u11"},
    "1bc5eb33adff4b92a5302de91577eb6d":{
      "scriptId":"u12"},
    "651cbf32e9474f0ea56aa3e663c9b1aa":{
      "scriptId":"u13"},
    "983f55c4f2ef491d89b466a33443b4f1":{
      "scriptId":"u14"},
    "c702b7b2870e40a89e63311fe26769de":{
      "scriptId":"u15"},
    "f1e3282618c7477395af9a7f6e69ec74":{
      "scriptId":"u16"},
    "b08043ca69b74838bb8081933948099f":{
      "scriptId":"u17"},
    "cfcdf4162a36460e85a930d4198e2194":{
      "scriptId":"u18"},
    "0937b8d12b4141c1962d122f7b58b8e0":{
      "scriptId":"u19"},
    "920caf78dc054bac9ae3dfacb41b2fa7":{
      "scriptId":"u20"},
    "d13b6e300b6c4b8299992b941b79abb3":{
      "scriptId":"u21"},
    "eb47c8ac0dc94f38a844e0afaa3cfe22":{
      "scriptId":"u22"},
    "d9f8a240768841718b2c7396ee63eb45":{
      "scriptId":"u23"},
    "50cc5815d6e94a53ae7e1c0993c538b3":{
      "scriptId":"u24"},
    "16ace0c5459348d79bc06057db940b73":{
      "scriptId":"u25"},
    "2a5e0c53a6ba4a258a0bd08017b92743":{
      "scriptId":"u26"},
    "fa5bdc7a2d5f4658ac69229a8f9ab199":{
      "scriptId":"u27"},
    "417652d834764ca5ab8b037e085ee507":{
      "scriptId":"u28"},
    "102f43a47cc54d5d916007bbc1770986":{
      "scriptId":"u29"},
    "d59a64690a6347bcb701f9f9541ff34e":{
      "scriptId":"u30"}}});