$axure.loadCurrentPage({
  "url":"editnickname.html",
  "generationDate":new Date(1425627273993.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0dd0ef5b661842dabab36b31ef9340b5",
    "type":"Axure:Page",
    "name":"editNickname",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"832ffc4d7ae04595bcdc95989e0e39d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a54ee7dd93b43da923a6332c70428af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/slide/u0.png"}},
{
          "id":"1b418920ead6484cb627fa611813a4c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5909d08d9acc4753af3f5fc269127a6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/signup/u2.png"}},
{
          "id":"d1818a8296da4cec9f0f19d99849011c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":15,
              "y":15},
            "size":{
              "width":30,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95b452abe2a74bb4855b37e22c9c22d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":15,
                  "y":15},
                "size":{
                  "width":30,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/signup/u4.png"}},
{
          "id":"d059dcfda1004feeb8261ad9086ff37e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "location":{
              "x":30,
              "y":87},
            "size":{
              "width":61,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"132f4ab2adae45debedaaff0a08c9925",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "location":{
                  "x":30,
                  "y":87},
                "size":{
                  "width":61,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0724275ca6344bc8baf41cec59b7e08c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":118},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index_1/u6_line.png"}},
{
          "id":"fcdff2e369754b64969bcf2edb434d3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":288,
              "y":28},
            "size":{
              "width":27,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a76e7876c2af47148b5205f1b9d84849",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":288,
                  "y":28},
                "size":{
                  "width":27,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (动态面板),<br>切换 (形状)",
                      "objectsToFades":[{
                          "objectPath":["8085c6b5ebfe45b39c7b1ad7ee63683b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["919193be0c7e422cb2b3244e787add7c"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8085c6b5ebfe45b39c7b1ad7ee63683b",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":80,
              "y":60},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"22fe049da4494b51b8288def49d4d0ac",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"919193be0c7e422cb2b3244e787add7c",
                  "label":"",
                  "parentDynamicPanel":"8085c6b5ebfe45b39c7b1ad7ee63683b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontWeight":"900",
                    "size":{
                      "width":200,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a0b2a864437d4ca6b7aae9c7c71ef661",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8085c6b5ebfe45b39c7b1ad7ee63683b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontWeight":"900",
                        "size":{
                          "width":200,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/signup/u17.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "832ffc4d7ae04595bcdc95989e0e39d2":{
      "scriptId":"u0"},
    "8a54ee7dd93b43da923a6332c70428af":{
      "scriptId":"u1"},
    "1b418920ead6484cb627fa611813a4c2":{
      "scriptId":"u2"},
    "5909d08d9acc4753af3f5fc269127a6a":{
      "scriptId":"u3"},
    "d1818a8296da4cec9f0f19d99849011c":{
      "scriptId":"u4"},
    "95b452abe2a74bb4855b37e22c9c22d1":{
      "scriptId":"u5"},
    "d059dcfda1004feeb8261ad9086ff37e":{
      "scriptId":"u6"},
    "132f4ab2adae45debedaaff0a08c9925":{
      "scriptId":"u7"},
    "0724275ca6344bc8baf41cec59b7e08c":{
      "scriptId":"u8"},
    "fcdff2e369754b64969bcf2edb434d3e":{
      "scriptId":"u9"},
    "a76e7876c2af47148b5205f1b9d84849":{
      "scriptId":"u10"},
    "8085c6b5ebfe45b39c7b1ad7ee63683b":{
      "scriptId":"u11"},
    "919193be0c7e422cb2b3244e787add7c":{
      "scriptId":"u12"},
    "a0b2a864437d4ca6b7aae9c7c71ef661":{
      "scriptId":"u13"}}});