$axure.loadCurrentPage({
  "url":"客服电话.html",
  "generationDate":new Date(1425625658809.57),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bb9ac46f72bd4c6a85b11d2ff19e969f",
    "type":"Axure:Page",
    "name":"客服电话",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFF666666},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7ebb2a9a61684106ad8193d835a0c3a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":16,
              "y":9},
            "size":{
              "width":1060,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5c1677cf5b54fa89c73b330f43d57a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":16,
                  "y":9},
                "size":{
                  "width":1060,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服电话/u0.png"}},
{
          "id":"25839b420b3f486a8cd3ae0796722bd8",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":88},
            "size":{
              "width":600,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f88e74c40304cc586104db562e8c867",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":600,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1789e6b1b7534a78b03d4f0e237c3a3f",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ecf3878a5a2c458fa7ee636c661427dc",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 工单管理",
                              "target":{
                                "targetType":"page",
                                "url":"工单管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u43.png"}},
{
                  "id":"e97bfc6f6c1d47a78ba249338b310426",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f30f52428c084d869d757f5b4ec70b06",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 账号管理",
                              "target":{
                                "targetType":"page",
                                "url":"账号管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u43.png"}},
{
                  "id":"dfc6ddaff81946b7b62561954c3a19e4",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4f7aea6984174d1380e64c0b2995afcb",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 奖品管理",
                              "target":{
                                "targetType":"page",
                                "url":"奖品管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u43.png"}},
{
                  "id":"7f273ac7866147d097c8e5e7275a1bdd",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"da96d04551e3479bbd76b0c735b8b984",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 积分中心",
                              "target":{
                                "targetType":"page",
                                "url":"积分中心.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u43.png"}},
{
                  "id":"3d25b79499724fc78dcc3ec78f2006e1",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c2e07be49b5a4f7982ed4d52ace243ae",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 系统设置",
                              "target":{
                                "targetType":"page",
                                "url":"系统设置.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u43.png"}},
{
                  "id":"fb4a49bdda9041bebe61fbd8b963b10e",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e3abf58e583a4893bed865bf1d38f0f2",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":500,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 版本管理",
                              "target":{
                                "targetType":"page",
                                "url":"版本管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u53.png"}}]}]},
{
          "id":"4297d0ca76ed4311a03e8ed47e48df73",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":232,
              "y":31},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统设置",
                      "target":{
                        "targetType":"page",
                        "url":"系统设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"002db2d82254473ab56dd0fcd7c3aa1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":190,
              "y":179},
            "size":{
              "width":700,
              "height":501}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f6afec2e8ce4064b6c35d04eb760a34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":190,
                  "y":179},
                "size":{
                  "width":700,
                  "height":501}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服电话/u17.png"}},
{
          "id":"c17271d36e6944348fd50eb284682e66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":110,
              "y":37},
            "size":{
              "width":104,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cb51ec4bc264913a66a7851570cc18d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":110,
                  "y":37},
                "size":{
                  "width":104,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"311cf3a701fc4b5c935545566c776212",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":268,
              "y":250},
            "size":{
              "width":512,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b395d3b6ef8f47f18e95059992122326",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":124,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"81e978749822483ea3c6ef1879c297df",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":124,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客服电话/u22.png"}},
{
              "id":"326b7d04ac214c699dbf0574b8a9178b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":124,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a4940aaaa714df9b362a2df322e9f37",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":124,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客服电话/u22.png"}},
{
              "id":"fe49b473b4744aceb0c57ada55a9fc1d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":124,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"34929f57dc15453d95729f9212b97a6a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":124,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客服电话/u38.png"}},
{
              "id":"0ffa6c61200d4b2d96d18fdea9cb8a70",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":234,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"334b2c66f3d043ed981adc6560cfd87c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":234,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/系统账号/u33.png"}},
{
              "id":"0a5ea5ac9d7649e481b3319fbb941a04",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":234,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"05e2a7de969c40d48be420b9400817a2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":234,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/系统账号/u33.png"}},
{
              "id":"ebed555be27c4333bff25809ef208fbc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":234,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"68c1b398d0bf45dda6c1228192d6052d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":234,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/系统账号/u45.png"}},
{
              "id":"b3fb0a86cbc8464d845dd7c16ffc8e94",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":334,
                  "y":0},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"35aa8069e0aa4de39f88ce086b7f5aac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":334,
                      "y":0},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客服电话/u28.png"}},
{
              "id":"6c63dfa6fa9c44458e578b4144741a60",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":334,
                  "y":30},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cf719997e1284918ba7d95bf839d9aec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":334,
                      "y":30},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客服电话/u28.png"}},
{
              "id":"b41c18f25d7f48c1b620880e10dec394",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":334,
                  "y":60},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"89f970642a04415ab9f8e1ab89e94a40",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":334,
                      "y":60},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客服电话/u44.png"}},
{
              "id":"928caf6b32d94652af92c91e31fda789",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":0},
                "size":{
                  "width":110,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"624fd725adf54aaf93b6ab25aa6a34d4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":0},
                    "size":{
                      "width":110,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客服电话/u24.png"}},
{
              "id":"fdb466bc757c491c8f9f4abe53485307",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":30},
                "size":{
                  "width":110,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"27b781ea549b4966aa3faed6d2c270f7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":30},
                    "size":{
                      "width":110,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客服电话/u24.png"}},
{
              "id":"a456406e154c48979e3ebd039a93edd3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":60},
                "size":{
                  "width":110,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0c6edb1037ed490dba790af17935d980",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":60},
                    "size":{
                      "width":110,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客服电话/u40.png"}}]},
{
          "id":"861dd7aa37974a42a9e5f8d392d958c8",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":599,
              "y":118},
            "size":{
              "width":100,
              "height":183}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f960564bef34f128027c796fae480ed",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":100,
                  "height":183}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0083e9aa85a24d0ba1ec09f6deb9eb3f",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a33bed9ec99240dc8824c645a2347579",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 系统设置",
                              "target":{
                                "targetType":"page",
                                "url":"系统设置.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/关于/u36.png"}},
{
                  "id":"eb125c108c554ed88d01cf6ab022d53e",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":93},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a65dbc834e50422ca003f18946db2547",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":93},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 意见反馈",
                              "target":{
                                "targetType":"page",
                                "url":"意见反馈.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/关于/u42.png"}},
{
                  "id":"4d267e200ae443609e923d5d1d415c2a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":123},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"29a7f69fefac4365aabaeebc8fa4a129",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":123},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 关于",
                              "target":{
                                "targetType":"page",
                                "url":"关于.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/关于/u42.png"}},
{
                  "id":"3e91970a3fe34bc6b14c3f76550a745d",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":153},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f670d04fa1df4859a42a3d7f528901de",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":153},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 客服电话",
                              "target":{
                                "targetType":"page",
                                "url":"客服电话.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/工单管理/u53.png"}},
{
                  "id":"429590f3cd6847f2b2518cd9a60fc8a5",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":31},
                    "size":{
                      "width":100,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9c788515cf1745d194db5d2b15befd61",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":31},
                        "size":{
                          "width":100,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 工单设置",
                              "target":{
                                "targetType":"page",
                                "url":"工单设置.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/关于/u36.png"}},
{
                  "id":"3bfbe9fa78a54044a05f734253369984",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":62},
                    "size":{
                      "width":100,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"44e7d5f348d44be18758be24293f75b2",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":62},
                        "size":{
                          "width":100,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 积分说明",
                              "target":{
                                "targetType":"page",
                                "url":"积分说明.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/关于/u36.png"}}]}]},
{
          "id":"3876ec58cee847048a37c7cebf20df07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":201,
              "y":150},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"756601247db042028590bf5592c26506",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":201,
                  "y":150},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a37ab1ea801940ca959c18c2f862ecd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":268,
              "y":152},
            "size":{
              "width":11,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ae9bd1c94ea47a3963a4d320f649d04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":268,
                  "y":152},
                "size":{
                  "width":11,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f52dfd3d14de4d15a3af3541ba7b8832",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":284,
              "y":150},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec9e9817d50d486098b40bd440d5d3ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":284,
                  "y":150},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d51559809b747069b34d4b4e1dab2b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000099,
              "opacity":1},
            "location":{
              "x":699,
              "y":286},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4c5bed198574f088ee3b500f6289219",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000099,
                  "opacity":1},
                "location":{
                  "x":699,
                  "y":286},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 新增编辑电话",
                      "objectsToFades":[{
                          "objectPath":["b91192deeb3f49929cd231cf9b6b98f6"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20a1072f72c444ef99e82ae84db3ed5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000099,
              "opacity":1},
            "location":{
              "x":745,
              "y":286},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f7bdda6f99041dfa569b5df8a0f841f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000099,
                  "opacity":1},
                "location":{
                  "x":745,
                  "y":286},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b626cf288c54548b7af1c9f9a9e170d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":760,
              "y":190},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 新增编辑电话",
                      "objectsToFades":[{
                          "objectPath":["b91192deeb3f49929cd231cf9b6b98f6"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"b91192deeb3f49929cd231cf9b6b98f6",
          "label":"新增编辑电话",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":369,
              "y":280},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"df2af74cd8be4656b0c7d7ac8b8fd30a",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5d9fb24cb28d40e795a6d36b168367f1",
                  "label":"",
                  "parentDynamicPanel":"b91192deeb3f49929cd231cf9b6b98f6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "size":{
                      "width":330,
                      "height":150}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"18e24079d58a43e892fc0644ec1efc50",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b91192deeb3f49929cd231cf9b6b98f6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "size":{
                          "width":330,
                          "height":150}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/客服电话/u72.png"}},
{
                  "id":"757b4579ae064ccd89051bace36e5e4c",
                  "label":"",
                  "parentDynamicPanel":"b91192deeb3f49929cd231cf9b6b98f6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":50,
                      "y":17},
                    "size":{
                      "width":66,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0e7a440bbce7483c94680ab2b0f168ce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b91192deeb3f49929cd231cf9b6b98f6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":50,
                          "y":17},
                        "size":{
                          "width":66,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9b99274eabc044b88b0d77ea00250628",
                  "label":"",
                  "parentDynamicPanel":"b91192deeb3f49929cd231cf9b6b98f6",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":120,
                      "y":15},
                    "size":{
                      "width":130,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"106f22c03c8f4b0ab56e315518c0ae4c",
                  "label":"",
                  "parentDynamicPanel":"b91192deeb3f49929cd231cf9b6b98f6",
                  "panelIndex":0,
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":50,
                      "y":95},
                    "size":{
                      "width":80,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 新增编辑电话",
                              "objectsToFades":[{
                                  "objectPath":["b91192deeb3f49929cd231cf9b6b98f6"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"cc746c536a9142139684cfcb311b4608",
                  "label":"",
                  "parentDynamicPanel":"b91192deeb3f49929cd231cf9b6b98f6",
                  "panelIndex":0,
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":170,
                      "y":95},
                    "size":{
                      "width":80,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 新增编辑电话",
                              "objectsToFades":[{
                                  "objectPath":["b91192deeb3f49929cd231cf9b6b98f6"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"40bca039558f4b429d4701534be213c6",
                  "label":"",
                  "parentDynamicPanel":"b91192deeb3f49929cd231cf9b6b98f6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":67,
                      "y":46},
                    "size":{
                      "width":40,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"84e18f840ed249edad11bec37285653d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b91192deeb3f49929cd231cf9b6b98f6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":67,
                          "y":46},
                        "size":{
                          "width":40,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e58442be57014ea09491f1b8c6659ca7",
                  "label":"",
                  "parentDynamicPanel":"b91192deeb3f49929cd231cf9b6b98f6",
                  "panelIndex":0,
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":117,
                      "y":46},
                    "size":{
                      "width":133,
                      "height":22}},
                  "adaptiveStyles":{
}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"15c5aae6b598456eba610f1bbe110fc8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":786,
              "y":146},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统设置",
                      "target":{
                        "targetType":"page",
                        "url":"系统设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "7ebb2a9a61684106ad8193d835a0c3a2":{
      "scriptId":"u0"},
    "a5c1677cf5b54fa89c73b330f43d57a1":{
      "scriptId":"u1"},
    "25839b420b3f486a8cd3ae0796722bd8":{
      "scriptId":"u2"},
    "3f88e74c40304cc586104db562e8c867":{
      "scriptId":"u3"},
    "1789e6b1b7534a78b03d4f0e237c3a3f":{
      "scriptId":"u4"},
    "ecf3878a5a2c458fa7ee636c661427dc":{
      "scriptId":"u5"},
    "e97bfc6f6c1d47a78ba249338b310426":{
      "scriptId":"u6"},
    "f30f52428c084d869d757f5b4ec70b06":{
      "scriptId":"u7"},
    "dfc6ddaff81946b7b62561954c3a19e4":{
      "scriptId":"u8"},
    "4f7aea6984174d1380e64c0b2995afcb":{
      "scriptId":"u9"},
    "7f273ac7866147d097c8e5e7275a1bdd":{
      "scriptId":"u10"},
    "da96d04551e3479bbd76b0c735b8b984":{
      "scriptId":"u11"},
    "3d25b79499724fc78dcc3ec78f2006e1":{
      "scriptId":"u12"},
    "c2e07be49b5a4f7982ed4d52ace243ae":{
      "scriptId":"u13"},
    "fb4a49bdda9041bebe61fbd8b963b10e":{
      "scriptId":"u14"},
    "e3abf58e583a4893bed865bf1d38f0f2":{
      "scriptId":"u15"},
    "4297d0ca76ed4311a03e8ed47e48df73":{
      "scriptId":"u16"},
    "002db2d82254473ab56dd0fcd7c3aa1f":{
      "scriptId":"u17"},
    "4f6afec2e8ce4064b6c35d04eb760a34":{
      "scriptId":"u18"},
    "c17271d36e6944348fd50eb284682e66":{
      "scriptId":"u19"},
    "3cb51ec4bc264913a66a7851570cc18d":{
      "scriptId":"u20"},
    "311cf3a701fc4b5c935545566c776212":{
      "scriptId":"u21"},
    "b395d3b6ef8f47f18e95059992122326":{
      "scriptId":"u22"},
    "81e978749822483ea3c6ef1879c297df":{
      "scriptId":"u23"},
    "928caf6b32d94652af92c91e31fda789":{
      "scriptId":"u24"},
    "624fd725adf54aaf93b6ab25aa6a34d4":{
      "scriptId":"u25"},
    "0ffa6c61200d4b2d96d18fdea9cb8a70":{
      "scriptId":"u26"},
    "334b2c66f3d043ed981adc6560cfd87c":{
      "scriptId":"u27"},
    "b3fb0a86cbc8464d845dd7c16ffc8e94":{
      "scriptId":"u28"},
    "35aa8069e0aa4de39f88ce086b7f5aac":{
      "scriptId":"u29"},
    "326b7d04ac214c699dbf0574b8a9178b":{
      "scriptId":"u30"},
    "4a4940aaaa714df9b362a2df322e9f37":{
      "scriptId":"u31"},
    "fdb466bc757c491c8f9f4abe53485307":{
      "scriptId":"u32"},
    "27b781ea549b4966aa3faed6d2c270f7":{
      "scriptId":"u33"},
    "0a5ea5ac9d7649e481b3319fbb941a04":{
      "scriptId":"u34"},
    "05e2a7de969c40d48be420b9400817a2":{
      "scriptId":"u35"},
    "6c63dfa6fa9c44458e578b4144741a60":{
      "scriptId":"u36"},
    "cf719997e1284918ba7d95bf839d9aec":{
      "scriptId":"u37"},
    "fe49b473b4744aceb0c57ada55a9fc1d":{
      "scriptId":"u38"},
    "34929f57dc15453d95729f9212b97a6a":{
      "scriptId":"u39"},
    "a456406e154c48979e3ebd039a93edd3":{
      "scriptId":"u40"},
    "0c6edb1037ed490dba790af17935d980":{
      "scriptId":"u41"},
    "ebed555be27c4333bff25809ef208fbc":{
      "scriptId":"u42"},
    "68c1b398d0bf45dda6c1228192d6052d":{
      "scriptId":"u43"},
    "b41c18f25d7f48c1b620880e10dec394":{
      "scriptId":"u44"},
    "89f970642a04415ab9f8e1ab89e94a40":{
      "scriptId":"u45"},
    "861dd7aa37974a42a9e5f8d392d958c8":{
      "scriptId":"u46"},
    "3f960564bef34f128027c796fae480ed":{
      "scriptId":"u47"},
    "0083e9aa85a24d0ba1ec09f6deb9eb3f":{
      "scriptId":"u48"},
    "a33bed9ec99240dc8824c645a2347579":{
      "scriptId":"u49"},
    "429590f3cd6847f2b2518cd9a60fc8a5":{
      "scriptId":"u50"},
    "9c788515cf1745d194db5d2b15befd61":{
      "scriptId":"u51"},
    "3bfbe9fa78a54044a05f734253369984":{
      "scriptId":"u52"},
    "44e7d5f348d44be18758be24293f75b2":{
      "scriptId":"u53"},
    "eb125c108c554ed88d01cf6ab022d53e":{
      "scriptId":"u54"},
    "a65dbc834e50422ca003f18946db2547":{
      "scriptId":"u55"},
    "4d267e200ae443609e923d5d1d415c2a":{
      "scriptId":"u56"},
    "29a7f69fefac4365aabaeebc8fa4a129":{
      "scriptId":"u57"},
    "3e91970a3fe34bc6b14c3f76550a745d":{
      "scriptId":"u58"},
    "f670d04fa1df4859a42a3d7f528901de":{
      "scriptId":"u59"},
    "3876ec58cee847048a37c7cebf20df07":{
      "scriptId":"u60"},
    "756601247db042028590bf5592c26506":{
      "scriptId":"u61"},
    "a37ab1ea801940ca959c18c2f862ecd0":{
      "scriptId":"u62"},
    "1ae9bd1c94ea47a3963a4d320f649d04":{
      "scriptId":"u63"},
    "f52dfd3d14de4d15a3af3541ba7b8832":{
      "scriptId":"u64"},
    "ec9e9817d50d486098b40bd440d5d3ad":{
      "scriptId":"u65"},
    "7d51559809b747069b34d4b4e1dab2b8":{
      "scriptId":"u66"},
    "c4c5bed198574f088ee3b500f6289219":{
      "scriptId":"u67"},
    "20a1072f72c444ef99e82ae84db3ed5d":{
      "scriptId":"u68"},
    "0f7bdda6f99041dfa569b5df8a0f841f":{
      "scriptId":"u69"},
    "3b626cf288c54548b7af1c9f9a9e170d":{
      "scriptId":"u70"},
    "b91192deeb3f49929cd231cf9b6b98f6":{
      "scriptId":"u71"},
    "5d9fb24cb28d40e795a6d36b168367f1":{
      "scriptId":"u72"},
    "18e24079d58a43e892fc0644ec1efc50":{
      "scriptId":"u73"},
    "757b4579ae064ccd89051bace36e5e4c":{
      "scriptId":"u74"},
    "0e7a440bbce7483c94680ab2b0f168ce":{
      "scriptId":"u75"},
    "9b99274eabc044b88b0d77ea00250628":{
      "scriptId":"u76"},
    "106f22c03c8f4b0ab56e315518c0ae4c":{
      "scriptId":"u77"},
    "cc746c536a9142139684cfcb311b4608":{
      "scriptId":"u78"},
    "40bca039558f4b429d4701534be213c6":{
      "scriptId":"u79"},
    "84e18f840ed249edad11bec37285653d":{
      "scriptId":"u80"},
    "e58442be57014ea09491f1b8c6659ca7":{
      "scriptId":"u81"},
    "15c5aae6b598456eba610f1bbe110fc8":{
      "scriptId":"u82"}}});