$axure.loadCurrentPage({
  "url":"getpassword.html",
  "generationDate":new Date(1425627273389.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9e61aee09094425491fa3f792af6050e",
    "type":"Axure:Page",
    "name":"getPassword",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8f0b32a1ee95467482f32f453308f3fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d375303858b43c6bb55dc1724818f67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/slide/u0.png"}},
{
          "id":"231b1d507c7d4839a07ee609cd82fd2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cb7bb13b098413db7ff3e3471ddce7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/signup/u2.png"}},
{
          "id":"bd19d4c7a140449a8ad3dc4719bdbd14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":15,
              "y":15},
            "size":{
              "width":30,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c284e72b18b346f68461b5f5147b9e64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":15,
                  "y":15},
                "size":{
                  "width":30,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 signIn",
                      "target":{
                        "targetType":"page",
                        "url":"signin.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/signup/u4.png"}},
{
          "id":"b2419437fc504200838c56850f2883b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":40,
              "y":80},
            "size":{
              "width":260,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c13087980b144203970d0d70f0b4665d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":80},
                "size":{
                  "width":260,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/signin/u4.png"}},
{
          "id":"316979d1fd424ce28f47d9d572bb9c53",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":40,
              "y":204},
            "size":{
              "width":260,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66a25c3c4de64d71b58800fe1087da2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":204},
                "size":{
                  "width":260,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/signin/u4.png"}},
{
          "id":"9f2ec1b23c554215b8e165d20a9da0b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":40,
              "y":264},
            "size":{
              "width":260,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"960d5ec39d424ca4b93d02797c74db7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":264},
                "size":{
                  "width":260,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/signin/u4.png"}},
{
          "id":"1ae1de42098343a29a8b4cb7fc26a067",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":40,
              "y":334},
            "size":{
              "width":260,
              "height":50},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca9727fd13b640c6af73cb62d46f5607",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":334},
                "size":{
                  "width":260,
                  "height":50},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (动态面板),<br>切换 (形状)",
                      "objectsToFades":[{
                          "objectPath":["3ae626daf6eb443f828e6626b9d270f0"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["96d14a1b75b5437c9e38122b519bb077"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/signin/u8.png"}},
{
          "id":"11825c6071a644808478310b6fb257ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":40,
              "y":140},
            "size":{
              "width":160,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf51b25b95c04fae8d782705f8017ccd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":140},
                "size":{
                  "width":160,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/signup/u12.png"}},
{
          "id":"2b2ba2b271dd4dde88598e500d5756c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":210,
              "y":140},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c707ee3c6a7c48a0aa1769da908907c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":210,
                  "y":140},
                "size":{
                  "width":90,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (动态面板),<br>切换 (形状)",
                      "objectsToFades":[{
                          "objectPath":["35f6ef97700049d8929cec6737c2b0b0"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["812826b770ba4f2ab3aea9a81c7c085e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/signup/u14.png"}},
{
          "id":"812826b770ba4f2ab3aea9a81c7c085e",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":70,
              "y":154},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"15790e2451bb41c1b5f868a8e3e2f039",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"35f6ef97700049d8929cec6737c2b0b0",
                  "label":"",
                  "parentDynamicPanel":"812826b770ba4f2ab3aea9a81c7c085e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontWeight":"900",
                    "size":{
                      "width":200,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"15fa772055db4292a317699626b6fcdb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"812826b770ba4f2ab3aea9a81c7c085e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontWeight":"900",
                        "size":{
                          "width":200,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/signup/u17.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"3ae626daf6eb443f828e6626b9d270f0",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":70,
              "y":204},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 signIn",
                      "target":{
                        "targetType":"page",
                        "url":"signin.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"d85e5da119174e3ba951dfb479450c72",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"96d14a1b75b5437c9e38122b519bb077",
                  "label":"",
                  "parentDynamicPanel":"3ae626daf6eb443f828e6626b9d270f0",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontWeight":"900",
                    "size":{
                      "width":200,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"08f168d8e7db4b24b423e69397e5fa53",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3ae626daf6eb443f828e6626b9d270f0",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontWeight":"900",
                        "size":{
                          "width":200,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/signup/u17.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "8f0b32a1ee95467482f32f453308f3fb":{
      "scriptId":"u0"},
    "5d375303858b43c6bb55dc1724818f67":{
      "scriptId":"u1"},
    "231b1d507c7d4839a07ee609cd82fd2b":{
      "scriptId":"u2"},
    "6cb7bb13b098413db7ff3e3471ddce7a":{
      "scriptId":"u3"},
    "bd19d4c7a140449a8ad3dc4719bdbd14":{
      "scriptId":"u4"},
    "c284e72b18b346f68461b5f5147b9e64":{
      "scriptId":"u5"},
    "b2419437fc504200838c56850f2883b3":{
      "scriptId":"u6"},
    "c13087980b144203970d0d70f0b4665d":{
      "scriptId":"u7"},
    "316979d1fd424ce28f47d9d572bb9c53":{
      "scriptId":"u8"},
    "66a25c3c4de64d71b58800fe1087da2d":{
      "scriptId":"u9"},
    "9f2ec1b23c554215b8e165d20a9da0b1":{
      "scriptId":"u10"},
    "960d5ec39d424ca4b93d02797c74db7b":{
      "scriptId":"u11"},
    "1ae1de42098343a29a8b4cb7fc26a067":{
      "scriptId":"u12"},
    "ca9727fd13b640c6af73cb62d46f5607":{
      "scriptId":"u13"},
    "11825c6071a644808478310b6fb257ed":{
      "scriptId":"u14"},
    "cf51b25b95c04fae8d782705f8017ccd":{
      "scriptId":"u15"},
    "2b2ba2b271dd4dde88598e500d5756c1":{
      "scriptId":"u16"},
    "c707ee3c6a7c48a0aa1769da908907c2":{
      "scriptId":"u17"},
    "812826b770ba4f2ab3aea9a81c7c085e":{
      "scriptId":"u18"},
    "35f6ef97700049d8929cec6737c2b0b0":{
      "scriptId":"u19"},
    "15fa772055db4292a317699626b6fcdb":{
      "scriptId":"u20"},
    "3ae626daf6eb443f828e6626b9d270f0":{
      "scriptId":"u21"},
    "96d14a1b75b5437c9e38122b519bb077":{
      "scriptId":"u22"},
    "08f168d8e7db4b24b423e69397e5fa53":{
      "scriptId":"u23"}}});