$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1425627273429.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c31d9cf3f9dc4c0ebce278147875c15e",
    "type":"Axure:Page",
    "name":"home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"846eb457eb064525b354b2c9a325c358",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":20,
              "y":10},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93486d42a2af46619375f5513dfd3a69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":20,
                  "y":10},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/slide/u0.png"}},
{
          "id":"efd192258c2343868cd021fcaac86451",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":20,
              "y":10},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d220d2877e24c518cb713b0ee472d96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":20,
                  "y":10},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/signup/u2.png"}},
{
          "id":"eea101b2019943d499c7b6d9b6f78e27",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":25,
              "y":15},
            "size":{
              "width":30,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6424909562934677bda3ea6fe0132850",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":25,
                  "y":15},
                "size":{
                  "width":30,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/signup/u4.png"}},
{
          "id":"d81bc46a93274f6ebb5938428e6eb361",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":40,
              "y":269},
            "size":{
              "width":270,
              "height":50},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79aacda566c640799b0ff302b4745822",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":40,
                  "y":269},
                "size":{
                  "width":270,
                  "height":50},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 home1",
                      "target":{
                        "targetType":"page",
                        "url":"home1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u6.png"}},
{
          "id":"71764b580fe4499da13af6e64352f4f2",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":58,
              "y":18},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8d278bef70e43b6ac3b104361941407",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":58,
                  "y":18},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u8.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "846eb457eb064525b354b2c9a325c358":{
      "scriptId":"u0"},
    "93486d42a2af46619375f5513dfd3a69":{
      "scriptId":"u1"},
    "efd192258c2343868cd021fcaac86451":{
      "scriptId":"u2"},
    "5d220d2877e24c518cb713b0ee472d96":{
      "scriptId":"u3"},
    "eea101b2019943d499c7b6d9b6f78e27":{
      "scriptId":"u4"},
    "6424909562934677bda3ea6fe0132850":{
      "scriptId":"u5"},
    "d81bc46a93274f6ebb5938428e6eb361":{
      "scriptId":"u6"},
    "79aacda566c640799b0ff302b4745822":{
      "scriptId":"u7"},
    "71764b580fe4499da13af6e64352f4f2":{
      "scriptId":"u8"},
    "b8d278bef70e43b6ac3b104361941407":{
      "scriptId":"u9"}}});