$axure.loadCurrentPage({
  "url":"exchange.html",
  "generationDate":new Date(1425627274302.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"19c95fdb4eb94e6fa54821e688c22c5c",
    "type":"Axure:Page",
    "name":"exchange",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"58fffd0eb8b04fe0ad9962866fa5ae17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3364fbec08447bd891c65006791462f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/slide/u0.png"}},
{
          "id":"7ce2c9e7d9334b718b7531dfc7efca08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c00fc64f630b423281655dfc8d05ec6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/signup/u2.png"}},
{
          "id":"477052e40d4d4afcb55cd9979b7fd68a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":15,
              "y":15},
            "size":{
              "width":30,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1be8e230518f4fe7a6524e50c79f5ef7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":15,
                  "y":15},
                "size":{
                  "width":30,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 home",
                      "target":{
                        "targetType":"page",
                        "url":"home_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/signup/u4.png"}},
{
          "id":"6cbad77126bb4e58a74c49be7d489747",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":264,
              "y":12},
            "size":{
              "width":54,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e246c5f534c0429b81e00d228f2769d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":264,
                  "y":12},
                "size":{
                  "width":54,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 history",
                      "target":{
                        "targetType":"page",
                        "url":"history.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ea34d13955e497cbad2c851a506f559",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":90},
            "size":{
              "width":92,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b11a257f08734ac7a18877f0792aa863",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":90},
                "size":{
                  "width":92,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/exchange/u8.png"}},
{
          "id":"a8571219504642eea9760e21e22453ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "location":{
              "x":137,
              "y":90},
            "size":{
              "width":81,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0522bec11f704a0ea2ab945e3848fdb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "location":{
                  "x":137,
                  "y":90},
                "size":{
                  "width":81,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"227f1f2969174cba8c1f7322e2d1f527",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"900",
            "lineSpacing":"18px",
            "location":{
              "x":135,
              "y":141},
            "size":{
              "width":170,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e120547648d407c833bdbd89846857a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"900",
                "lineSpacing":"18px",
                "location":{
                  "x":135,
                  "y":141},
                "size":{
                  "width":170,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5cb268da66f407d839ffd1e248b38f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":201},
            "size":{
              "width":288,
              "height":50},
            "cornerRadiusTopLeft":"76"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4f50569e7324e618407083a78f16872",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":201},
                "size":{
                  "width":288,
                  "height":50},
                "cornerRadiusTopLeft":"76"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 history4",
                      "target":{
                        "targetType":"page",
                        "url":"history4.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/exchange/u14.png"}},
{
          "id":"a5de378b20d74948848d31f9195ff966",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "location":{
              "x":30,
              "y":404},
            "size":{
              "width":288,
              "height":50},
            "cornerRadiusTopLeft":"76"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49f21f3e255b41a09639d99346c150cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":404},
                "size":{
                  "width":288,
                  "height":50},
                "cornerRadiusTopLeft":"76"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 history4",
                      "target":{
                        "targetType":"page",
                        "url":"history4.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/exchange/u14.png"}},
{
          "id":"971ce9ced5534861802673d3a1a4bf01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"900",
            "location":{
              "x":132,
              "y":118},
            "size":{
              "width":79,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20162f863e344bd6a8086159b73b1146",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"900",
                "location":{
                  "x":132,
                  "y":118},
                "size":{
                  "width":79,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fea59ab40b324cccb34e066c6a7ea9db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"900",
            "location":{
              "x":256,
              "y":90},
            "size":{
              "width":54,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d5556fbd8714414bdfb2d4c9bd2adc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"900",
                "location":{
                  "x":256,
                  "y":90},
                "size":{
                  "width":54,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6f2195ffc324d22a126be168eda712f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"900",
            "location":{
              "x":256,
              "y":291},
            "size":{
              "width":54,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71f06fb3e60f411fb6c244509f084fa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"900",
                "location":{
                  "x":256,
                  "y":291},
                "size":{
                  "width":54,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"961f27c020de4a459f2fe9dda1637392",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":35,
              "y":291},
            "size":{
              "width":92,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7cae169d86f4347b239ae07b4c7bbde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":35,
                  "y":291},
                "size":{
                  "width":92,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/exchange/u8.png"}},
{
          "id":"1c9e040a9f584ceeac23d480724c4ac5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "location":{
              "x":142,
              "y":291},
            "size":{
              "width":81,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8505fedfbef547e59e9b1ae43d1acc32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "location":{
                  "x":142,
                  "y":291},
                "size":{
                  "width":81,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e9e525c76b446e2a2188b45bc23eadb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"900",
            "lineSpacing":"18px",
            "location":{
              "x":140,
              "y":342},
            "size":{
              "width":170,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d1447d189fa47239ef0c4c690238e17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"900",
                "lineSpacing":"18px",
                "location":{
                  "x":140,
                  "y":342},
                "size":{
                  "width":170,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee41fcf19f5a41f5b12c5f733046b362",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"900",
            "location":{
              "x":137,
              "y":319},
            "size":{
              "width":79,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad512553b514418f8924b9b5f24039d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"900",
                "location":{
                  "x":137,
                  "y":319},
                "size":{
                  "width":79,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "58fffd0eb8b04fe0ad9962866fa5ae17":{
      "scriptId":"u0"},
    "f3364fbec08447bd891c65006791462f":{
      "scriptId":"u1"},
    "7ce2c9e7d9334b718b7531dfc7efca08":{
      "scriptId":"u2"},
    "c00fc64f630b423281655dfc8d05ec6f":{
      "scriptId":"u3"},
    "477052e40d4d4afcb55cd9979b7fd68a":{
      "scriptId":"u4"},
    "1be8e230518f4fe7a6524e50c79f5ef7":{
      "scriptId":"u5"},
    "6cbad77126bb4e58a74c49be7d489747":{
      "scriptId":"u6"},
    "e246c5f534c0429b81e00d228f2769d9":{
      "scriptId":"u7"},
    "8ea34d13955e497cbad2c851a506f559":{
      "scriptId":"u8"},
    "b11a257f08734ac7a18877f0792aa863":{
      "scriptId":"u9"},
    "a8571219504642eea9760e21e22453ff":{
      "scriptId":"u10"},
    "0522bec11f704a0ea2ab945e3848fdb2":{
      "scriptId":"u11"},
    "227f1f2969174cba8c1f7322e2d1f527":{
      "scriptId":"u12"},
    "5e120547648d407c833bdbd89846857a":{
      "scriptId":"u13"},
    "f5cb268da66f407d839ffd1e248b38f7":{
      "scriptId":"u14"},
    "f4f50569e7324e618407083a78f16872":{
      "scriptId":"u15"},
    "a5de378b20d74948848d31f9195ff966":{
      "scriptId":"u16"},
    "49f21f3e255b41a09639d99346c150cf":{
      "scriptId":"u17"},
    "971ce9ced5534861802673d3a1a4bf01":{
      "scriptId":"u18"},
    "20162f863e344bd6a8086159b73b1146":{
      "scriptId":"u19"},
    "fea59ab40b324cccb34e066c6a7ea9db":{
      "scriptId":"u20"},
    "6d5556fbd8714414bdfb2d4c9bd2adc7":{
      "scriptId":"u21"},
    "f6f2195ffc324d22a126be168eda712f":{
      "scriptId":"u22"},
    "71f06fb3e60f411fb6c244509f084fa6":{
      "scriptId":"u23"},
    "961f27c020de4a459f2fe9dda1637392":{
      "scriptId":"u24"},
    "b7cae169d86f4347b239ae07b4c7bbde":{
      "scriptId":"u25"},
    "1c9e040a9f584ceeac23d480724c4ac5":{
      "scriptId":"u26"},
    "8505fedfbef547e59e9b1ae43d1acc32":{
      "scriptId":"u27"},
    "8e9e525c76b446e2a2188b45bc23eadb":{
      "scriptId":"u28"},
    "1d1447d189fa47239ef0c4c690238e17":{
      "scriptId":"u29"},
    "ee41fcf19f5a41f5b12c5f733046b362":{
      "scriptId":"u30"},
    "ad512553b514418f8924b9b5f24039d5":{
      "scriptId":"u31"}}});