$axure.loadCurrentPage({
  "url":"bankaccount.html",
  "generationDate":new Date(1425627274121.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"afe4a034f886483f9d43eaaa10982c2c",
    "type":"Axure:Page",
    "name":"bankAccount",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"52e64663c5a44676aa4ae539256cdb4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"833ded4c213b479aae8f9737cdcfb992",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/slide/u0.png"}},
{
          "id":"bc9761b35dda46f6ad1ee0455374b7cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21651c83559b4a3680bbdee59c22792f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/signup/u2.png"}},
{
          "id":"b109056341ae4d8bbbba9fe1eadc6b99",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":15,
              "y":15},
            "size":{
              "width":30,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5c043b92c234a08a324c63950448db5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":15,
                  "y":15},
                "size":{
                  "width":30,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/signup/u4.png"}},
{
          "id":"a95f1f2fac764749b62dab96202af084",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":288,
              "y":28},
            "size":{
              "width":27,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd872739d20d41229a2156e62a1d927d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":288,
                  "y":28},
                "size":{
                  "width":27,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (动态面板),<br>切换 (形状)",
                      "objectsToFades":[{
                          "objectPath":["ee80931da9ba4ca7a83f06203d27f826"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2585ceadafc942caa54bd7ca31451ead"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e537ec48e0ba4da98f6660849555c4ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":30,
              "y":149},
            "size":{
              "width":101,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d190487b791b458388637f5815cd1af8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":30,
                  "y":149},
                "size":{
                  "width":101,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b5fd24c3e464105bc047c8358673763",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":180},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index_1/u6_line.png"}},
{
          "id":"3cebf4a36822481c8b69f350bb54dcc5",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":90},
            "size":{
              "width":285,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"ee80931da9ba4ca7a83f06203d27f826",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":70,
              "y":60},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"1fd246ba68d64aa99015c0bc3fdd989f",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2585ceadafc942caa54bd7ca31451ead",
                  "label":"",
                  "parentDynamicPanel":"ee80931da9ba4ca7a83f06203d27f826",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontWeight":"900",
                    "size":{
                      "width":200,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6f0a888be8e74cf48ba4c0012f533392",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ee80931da9ba4ca7a83f06203d27f826",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontWeight":"900",
                        "size":{
                          "width":200,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/signup/u17.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "52e64663c5a44676aa4ae539256cdb4f":{
      "scriptId":"u0"},
    "833ded4c213b479aae8f9737cdcfb992":{
      "scriptId":"u1"},
    "bc9761b35dda46f6ad1ee0455374b7cc":{
      "scriptId":"u2"},
    "21651c83559b4a3680bbdee59c22792f":{
      "scriptId":"u3"},
    "b109056341ae4d8bbbba9fe1eadc6b99":{
      "scriptId":"u4"},
    "e5c043b92c234a08a324c63950448db5":{
      "scriptId":"u5"},
    "a95f1f2fac764749b62dab96202af084":{
      "scriptId":"u6"},
    "fd872739d20d41229a2156e62a1d927d":{
      "scriptId":"u7"},
    "e537ec48e0ba4da98f6660849555c4ed":{
      "scriptId":"u8"},
    "d190487b791b458388637f5815cd1af8":{
      "scriptId":"u9"},
    "0b5fd24c3e464105bc047c8358673763":{
      "scriptId":"u10"},
    "3cebf4a36822481c8b69f350bb54dcc5":{
      "scriptId":"u11"},
    "ee80931da9ba4ca7a83f06203d27f826":{
      "scriptId":"u12"},
    "2585ceadafc942caa54bd7ca31451ead":{
      "scriptId":"u13"},
    "6f0a888be8e74cf48ba4c0012f533392":{
      "scriptId":"u14"}}});